### ISSUE TITLE
Use LightTransaction

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1008]
With https://github.com/iov-one/iov-core/pull/975 merged, we should do the following `BlockchainConnection` changes:

- [x] Create
`getTransaction: (id: TransactionId) => Promise<ConfirmedTransaction | FailedTransaction>;`.
This can later be used when clicking on transaction details from a transactions list. With the result of that, it should be possible to verify the signature locally.
- [x] Change interface to
`searchTx(query: TransactionQuery): Promise<ReadonlyArray<LightTransaction | FailedTransaction>>`
- [x] Change interface to
`listenTx(query: TransactionQuery): Stream<LightTransaction | FailedTransaction>`
- [x] Change interface to
`liveTx(query: TransactionQuery): Stream<LightTransaction | FailedTransaction>`

**Comment by willclarktech** [comment]
@webmaster128 Definitely `LightTransaction` in these cases rather than `ConfirmedTransaction<LightTransaction>`? What should be done with all the (now superfluous) information?

**Comment by webmaster128** [comment]
> Definitely LightTransaction in these cases rather than ConfirmedTransaction<LightTransaction>? 

Nope, my fault. `ConfirmedTransaction<LightTransaction>` is most likely the way to go. Feel free to do a plausibility check and error correction on the description above. It was more a sketch of the direction than a careful API design.

**Comment by willclarktech** [comment]
Does the scope of this issue also cover changing `TxCodec.parseBytes`? I.e. should it return a signed `LightTransaction` without a `creator`? (And therefore not require the `chainId` parameter.)

**Comment by webmaster128** [comment]
> Does the scope of this issue also cover changing TxCodec.parseBytes? I.e. should it return a signed LightTransaction without a creator? (And therefore not require the chainId parameter.)

Looking at the description

```
  /** parseBytes will recover bytes from the blockchain into a format we can use */
  readonly parseBytes: (bytes: PostableBytes, chainId: ChainId) => SignedTransaction;
```

I tend to say that `parseBytes` should be unchanged and be used as-is in the new `getTransaction`. However, if we need something similar for `LightTransaction`, it should be created at some proper place.

**Comment by willclarktech** [comment]
Does this also apply to depencies of these methods such as `watchSwaps`? (Relies on `liveTx` in at lease one case.)

**Comment by webmaster128** [comment]
> watchSwaps

As a quick and dirty solution, I'd call `getTransaction` for every `liveTx` event. This can easily be done as long as we do not have long lists of atomic swaps. This way, we can postpone the question.
