### ISSUE TITLE
Refactor Secp256k1Keypair to avoid using `unique symbol`

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1041]
https://github.com/iov-one/iov-core/blob/master/packages/iov-crypto/src/secp256k1.ts#L11

We shouldn't need to use a type-tagger at all.

**Comment by webmaster128** [comment]
Since the interface `Secp256k1Keypair` is not compatible to `Ed25519Keypair` anymore, we can simply use

```
export interface Secp256k1Keypair {
  readonly pubkey: Uint8Array;
  readonly privkey: Uint8Array;
};
```
