### ISSUE TITLE
Upgrade to weave 0.16

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1053]
not released yet

**Comment by willclarktech** [comment]
Do we want to diverge from Weave's versioning at this point? (Not sure how synchronised we've been so far.) Another option would be to have an empty release.

**Comment by webmaster128** [comment]
> Do we want to diverge from Weave's versioning at this point? (Not sure how synchronised we've been so far.)

We never tried to be in sync. This is just a coincidence
