### ISSUE TITLE
Streamline terminology for BNS encoding

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1082]
In BNS we have those three encodings for transactions and objects:

1. External facing types (e.g.  `Amount`, `RegisterUsernameTx`)
2. Protobuf types (e.g.  `codecImpl.coin.ICoin`, `codecImpl.username.IIssueTokenMsg`)
3. binary representation

We need proper verbs for the transitions:

- 1 -> 2
- 2 -> 3 (called "encode" by protobuf)
- 3 -> 2 (called "decode" by the protobuf)
- 2 -> 1

The term "parse" should probably disappear in this context, as it is used as a synonym for "decode" but does not match properly.

I wonder if there are better terms for 1->2/2->1 than "encode"/"decode".

**Comment by willclarktech** [comment]
How about "translateToProtobuf"/"translateFromProtobuf"?

**Comment by webmaster128** [comment]
In #1082 I rename the remaining functions for step 1. to encode* for consistency.

Going for

- 1 -> 2 "encode"
- 2 -> 3 "encode to binary" (not used much in our code)
- 3 -> 2 "decode from binary" (not used much in our code)
- 2 -> 1 "decode"

seems to be the most natural thing right now given how the codebase is written.
