### ISSUE TITLE
Forward look-up of an address.

### ISSUE THREAD

**Issue by kmw101** [iov-one/iov-core#1094]
The names and namespaces are to be obfuscated on chain. When doing a forward look-up there will need to be an extra step.

As a user I want to send 10 IOV to alice*iov, to create the send transaction there is a lookup to return the native IOV address which is then used in the sendTX message.

This is done by hashing alice*iov and then the look-up is done using the hashed address.

**Comment by webmaster128** [comment]
Not part of the current development roadmap. Closing for now.
