### ISSUE TITLE
Make iov-cli work with NodeJs 12+

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1097]
We get the error

```
>> (node:71798) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_REPL_INPUT] [ERR_INVALID_REPL_INPUT]: Listeners for `uncaughtException` cannot be used in the REPL
    at process.<anonymous> (repl.js:224:15)
    at process.emit (events.js:205:15)
    at process.EventEmitter.emit (domain.js:471:20)
    at process.emit (/place/node_modules/source-map-support/source-map-support.js:461:21)
    at _addListener (events.js:226:14)
    at process.addListener (events.js:274:10)
    at Object.C.useBackupModule (/place/node_modules/libsodium/dist/modules/libsodium.js:1:1244)
    at /place/node_modules/libsodium/dist/modules/libsodium.js:1:502840
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:71798) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

after https://github.com/nodejs/node/commit/c709c524fd674f3762b3da9e005f645255bc1e2f because of code compiled into `node_modules/libsodium/dist/modules/libsodium.js`.

**Comment by webmaster128** [comment]
Filed a bugreport in libsodium.js: https://github.com/jedisct1/libsodium.js/issues/205

**Comment by willclarktech** [comment]
@webmaster128 How do I reproduce this error?

**Comment by webmaster128** [comment]
> How do I reproduce this error?

* Build project
* Install nodeJs 12 or higher and make it the default for `#!/usr/bin/env node`
* Go to `packages/iov-cli` and run `./bin/iov-cli`

**Comment by willclarktech** [comment]
PR submitted to libsodium: https://github.com/jedisct1/libsodium/pull/853

**Comment by webmaster128** [comment]
I subscribed to https://github.com/jedisct1/libsodium.js releases. Let's see and wait. For now we can see this as a known limitation.

**Comment by webmaster128** [comment]
There is a new version of libsodium.js available. `"libsodium-wrappers": "^0.7.6",` should include the fix (untested)
