### ISSUE TITLE
Support all BNS governance proposal types

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1112]
As of https://github.com/iov-one/iov-core/pull/1109 we only support `AmendProtocol` but we should have structures and functions to be able to support all the others listed here: https://github.com/iov-one/iov-core/blob/721c761836904af0f3160fa4ba67b3f927e6efb2/packages/iov-bns-governance/src/proposals.ts#L9-L19

- [x] `AddCommitteeMember`: https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/v0.16.0/docs/proto/index.html#gov.UpdateElectorateMsg
- [x] `RemoveCommitteeMember`: https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/v0.16.0/docs/proto/index.html#gov.UpdateElectorateMsg
- [x] `AmendElectionRuleThreshold`: https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/v0.16.0/docs/proto/index.html#gov.UpdateElectionRuleMsg
- [x] `AmendElectionRuleQuorum`: https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/v0.16.0/docs/proto/index.html#gov.UpdateElectionRuleMsg (~~blocked by https://github.com/iov-one/weave/issues/869~~)
- [x] `AddValidator`: https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/v0.16.0/docs/proto/index.html#validators.SetValidatorsMsg
- [x] `RemoveValidator`: https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/v0.16.0/docs/proto/index.html#validators.SetValidatorsMsg
- [x] `ReleaseGuaranteeFunds`: https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/master/docs/proto/index.html#escrow.ReleaseMsg [CLARIFICATION REQUIRED]
- [x] `DistributeFunds`: https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/master/docs/proto/index.html#bnsd.ExecuteProposalBatchMsg and https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/master/docs/proto/index.html#cash.SendMsg [CLARIFICATION REQUIRED]
- [x] `AmendProtocol`

**Comment by webmaster128** [comment]
Guarantee funds are stored in an escrow, so `ReleaseGuaranteeFunds`/https://github.com/iov-one/iov-core/pull/1134 should be good and done.

**Comment by willclarktech** [comment]
@webmaster128 I think this is good to close now?

**Comment by webmaster128** [comment]
🎉
