### ISSUE TITLE
Research chain ID format for Bitcoin and Cosmos

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1129]
The [Chain IDs spec](https://github.com/iov-one/iov-core/blob/master/docs/chain-ids.md) should cover Bitcoin and Cosmos chains as well. In both cases we need to get an overview of how the native chain specifier looks like. Research needs to be done in order to ensure the chain ID specification

- can cover all chains of that class,
- the resulting format leads to unique identifiers within the entire blockchain space.

**Comment by davepuchyr** [comment]
Antoine started a Telegram channel on cosmos related to chainIds that's got good traction already.  It might be too noisy at the moment, but here it is: https://t.me/cosmoschainids.

**Comment by webmaster128** [comment]
Spec waiting for review/merge at https://github.com/ChainAgnostic/CAIPs/pull/9

**Comment by webmaster128** [comment]
Research done
