### ISSUE TITLE
Finalize generic blockchain interface

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#113]
This interface will be implemented by bcp-demo/bns direct connection, as well as bcp-proxy client connection. 

* Standardize on the types returned from bcp-proxy.
* Define a nice API around it, with subscriptions as well as queries
* Focus on usability and Observable/reactive patterns

**Comment by webmaster128** [comment]
Closing as outdated. BCP exists, works great and evolves every week.
