### ISSUE TITLE
Prepare chain ID spec for Lisk LIP-0009 chain identifier

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1149]
[LIP-0009](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0009.md) will create a new Lisk chain ID format. We should review/adapt our chain ID spec to ensure it will work for the new format as well.

**Comment by willclarktech** [comment]
lisk-sdk issue: https://github.com/LiskHQ/lisk-sdk/issues/4039

**Comment by webmaster128** [comment]
Done in https://github.com/ChainAgnostic/CAIPs/pull/9
