### ISSUE TITLE
Prefix IOV's chains with iov-*

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1150]
The BNS is called IOV Name Service now, which is powered by the IOV utility token.

So we should adapt the chain ID spec to prefix IOV's networks with `iov-`

**Comment by willclarktech** [comment]
@webmaster128 Will there be other issues for other BNS renamings? Are these on the MVP track?

**Comment by webmaster128** [comment]
@willclarktech Right now I only bother about the things that will end up as in-chain data, which is almost impossible to change later on. Those should be changed before mainnet launch. All the rest can stay as is.
