### ISSUE TITLE
Check bip39WordlistEnglish against BIP39

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1179]
Right now we use a wordlist from an npm package and we hope it is correct. I would like to check the value of

```ts
import bip39WordlistEnglish from "bip39/wordlists/english.json";
```

against the file `english.txt` from https://github.com/bitcoin/bips/tree/master/bip-0039 (sha256:2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda) and verify:

1. We can load `english.txt` from the speck into a test (binary) and the checksum matches
2. When split line-by-line, we get the exact same wordlist as `bip39WordlistEnglish`

This way we can verify the wordlist in the package is the same as in the spec. Looking at some of the latest commits to the wordlist, it seems worth checking them bit-by-bit:

- https://github.com/bitcoin/bips/commit/50c4f1255eed6b1c08ca9c20b4d8f380879ed2f5
- https://github.com/bitcoin/bips/commit/144ef37e5314f8f968b8abb5a6fe8038d32e46ce
- https://github.com/bitcoin/bips/commit/25f10b9f7bf844ebd98dc9ca6556228c3c34c44b

**Comment by willclarktech** [comment]
Closed in https://github.com/iov-one/iov-core/pull/1180
