### ISSUE TITLE
Replace hardcoded "tiov" prefixes in BnsConnection

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1188]
Currently we still have some hardcoded "tiov" address prefixes. These should be replaced for mainnet compatibility:
https://github.com/iov-one/iov-core/blob/master/packages/iov-bns/src/bnsconnection.ts#L666-L680

Easily fixed with `addressPrefix(this.chainId())`.

**Comment by webmaster128** [comment]
Done in #1189
