### ISSUE TITLE
Make CashConfiguration.minimalFee nullable

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1192]
In

```ts
export function decodeCashConfiguration(config: codecImpl.cash.Configuration): CashConfiguration {
  const minimalFee = decodeAmount(ensure(config.minimalFee, "minimalFee"));
  return {
    minimalFee: minimalFee,
  };
}
```

we need to handle the case that config.minimalFee null (or better falsy in general). The type of `CashConfiguration.minimalFee` becomes `Amount | null`.

See https://github.com/iov-one/weave/issues/921

**Comment by webmaster128** [comment]
As concluded in https://github.com/iov-one/weave/issues/921, it is easier for the backend to send us min fees in the form `Coin{0, 0, ""}` instead of making the field nullable. This structure is something that we should not expose outside of IOV-Core, since the ticker is missing. To handle this special case, we should have a `isZeroCoin(coin: coin.ICoin): boolean` helper that returns true if the quantity is 0 and does not look at the ticker at all. In case of a zero `minimalFee`, we should not even decode the value into a BCP `Amount`. Instead `CashConfiguration.minimalFee` should be set to `null`.

**Comment by willclarktech** [comment]
@webmaster128 How should this propagate out via e.g. `BnsConnection.getDefaultFee()`: a dummy fee or change those types too to allow `null`?

**Comment by webmaster128** [comment]
@willclarktech `BnsConnection.getDefaultFee()` should return a nullable result, so either `Amount | null` or `Amount | undefined`. The later would be compatible directly with `Fee.tokens`. I still have no clear general plan about this `undefined` vs `null` question.
