### ISSUE TITLE
New chain connector: Cosmos

### ISSUE THREAD

**Issue by kmw101** [iov-one/iov-core#1220]
Add a new chain connector to support Cosmos.

MVP: support Cosmos Hub and ATOM (we can generalise to other chains/tokens at a later point). We should be able to reuse our Tendermint code.

- [x] Research which transaction types we want to support
- [x] Test setup of Cosmos Hub node (https://hub.cosmos.network/docs/deploy-testnet.html)
- [x] Start Cosmos node in Travis
- [x] @iov/cosmos package setup
- [x] Encoding/decoding
- [x] Codec
- [x] Connection [MVP]
- [x] Connector

**Comment by willclarktech** [comment]
Based on modules listed here: https://github.com/cosmos/gaia/blob/master/docs/what-is-gaia.md

Transactions to include:
- `bank/send`: https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/internal/types/msgs.go#L10-L15

Transactions to exclude:
- `bank/multisend`: https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/internal/types/msgs.go#L57-L61
- `staking/*`: https://github.com/cosmos/cosmos-sdk/blob/master/x/staking/handler.go#L16-L41
- `distribution/*`: https://github.com/cosmos/cosmos-sdk/blob/master/x/distribution/handler.go#L12-L31
- `slashing/*`: https://github.com/cosmos/cosmos-sdk/blob/master/x/slashing/handler.go#L10-L24
- `gov/*`: https://github.com/cosmos/cosmos-sdk/blob/master/x/gov/handler.go#L10-L30

**Comment by willclarktech** [comment]
@webmaster128 Under which version should CHANGELOG entries appear?

**Comment by webmaster128** [comment]
> @webmaster128 Under which version should CHANGELOG entries appear?

I suggest collecting them at an extra place (here, wiki, private notes, Confluence, gist) and add them to the first release that publishes a @iov/cosmos package.

**Comment by willclarktech** [comment]
@webmaster128 OK to close this issue and open follow-ups for improvements eg RPC support?

**Comment by webmaster128** [comment]
👍 We just need to create an overview of what is missing before we can un-private @iov/cosmos. Using the chain IDs from https://github.com/ChainAgnostic/CAIPs/issues/5 is one open thing. Balance subscriptions would be needed for wallet integration.
