### ISSUE TITLE
Change type of escrowId to number

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1235]
Like in multisig contracts, those are sequences that can be represented as numbers (uint64).

~Non-breaking since escrow types are not exported.~

- [x] ReleaseEscrowTx, ReturnEscrowTx, UpdateEscrowPartiesTx
- [x] ReleaseEscrowAction
- [ ] escrowIdToAddress

**Comment by willclarktech** [comment]
Looks like this is breaking because `ReleaseEscrowAction` is exported from `@iov/bns`.
