### ISSUE TITLE
Encoding method names should be consistent

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1236]
The method names in https://github.com/iov-one/iov-core/blob/master/packages/iov-encoding/src/encoding.ts are inconsistent and confusing. We should use `to`/`from` with consistent directions between strings and arrays. The current situation:

1. `to` = array -> string; `from` = string -> array
    - `hex`
    - `base64`
    - `rfc3339` (in this case a date object not an array)
2. `to` = string -> array; `from` = array -> string
    - `ascii`
    - `utf8`

In my opinion the correct direction is 1 above, so the `ascii` and `utf8` methods should be renamed.

**Comment by webmaster128** [comment]
The naming results from the nature of those encodings, not from the string/array question. 1. are binary encodings and 2. are string encodings. See:

| Encoding | Input type     | Encoded type | Interpretation |
|----------|----------------|--------------|----------------|
| hex      | bytes          | string       | _to hex_ encodes bytes as hex |
| base64   | bytes          | string       | _to base64_ encodes bytes as base64 |
| ascii    | string         | bytes        | _to ascii_ encodes unicode string as ascii bytes |
| utf8     | string         | bytes        | _to utf8_ encodes unicode string as utf8 bytes |
| rfc3339  | Date           | string       | _to rfc3339_ encodes a Date as a RFR3339 string |

Doe this halp clarifying the situation?

**Comment by willclarktech** [comment]
Thanks, very helpful. I guess the clearest names would have both the source and destination, but probably those would be too cumbersome.
