### ISSUE TITLE
Circular dependency in @iov/bcp

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1245]
`atomicswaptypes.ts` imports from `transactions.ts` and vice versa.

**Comment by webmaster128** [comment]
We should build some tooling to create dependency graphs inside a package. Given a yaml file like 

```
'ConfigurationFile':
    
'database':

'UserProfile':
- 'database'
 
'MultiChainSigner':
 - 'ConfigurationFile'
 - 'network'
 - 'UserProfile'

'AccountManager':
 - 'MultiChainSigner'
 - 'UserProfile'

'Persona':
- 'AccountManager'
- 'MultiChainSigner'
- 'ConfigurationFile'
```

[depsight](https://github.com/webmaster128/depsight) can visualize it
