### ISSUE TITLE
Define chain ID format for Cosmos Hub

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1282]
Apparently after hard forks the ID of the Cosmos Hub blockchain changes. See eg https://github.com/cosmos/cosmos-sdk/wiki/Cosmos-Hub-1-Upgrade

This poses a problem for us in that keypairs are registered in combination with a chain ID and the keypair-chainID combination is assumed to be static. Possible solutions include:

1. Do nothing and require users to reregister their keypair with the new chain ID.
1. Provide tools to aid users in this kind of reregistration.
1. Define a static chain ID for Cosmos Hub and handle the change outside the IOV blockchain.
1. Revisit our entire chain ID specification.

**Comment by annatorok** [comment]
@willclarktech We should support Cosmos ecosystem (any chains on Cosmos), not only the Hubl
