### ISSUE TITLE
Add support for Tendermint RPC 0.32

### ISSUE THREAD

**Issue by jnaviask** [iov-one/iov-core#1283]
Hi, I tried to use your @iov/tendermint-rpc library today to connect to a tendermint testnet running v0.32.3, but I got an error that it's unsupported. Would it be possible to get support for this version? Thanks!

**Comment by willclarktech** [comment]
Hi @jnaviask, this will come in the near future. The reason we don't have it already is that [our Tendermint framework, weave](https://github.com/iov-one/weave) currently uses 0.31, so as soon as that updates we'll need corresponding updates in our client library. We might also need to update this independently as part of our work to [support Cosmos](https://github.com/iov-one/iov-core/issues/1220).

**Comment by webmaster128** [comment]
https://github.com/iov-one/iov-core/pull/1286 will be merged soon as if I understand correctly, it closes this issue. @jnaviask do you need that released on npm or can you work with local master of this repo for now (`yarn install && yarn build`; then the library is ready to use in `iov-core/packages/iov-tendermint-rpc`)?

**Comment by jnaviask** [comment]
@webmaster128 NPM would be ideal, thank you!

**Comment by webmaster128** [comment]
The package was published as @iov/tendermint-rpc version 1.1.0 to npm.

@jnaviask let us know if you have trouble using it or if you are missing features. We're happy to grow our userbase beyond Weave-based blockchains.

Closing this now, please follow up with more specific tickets. Thanks!
