### ISSUE TITLE
Implement mutable product fees

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1289]
Requirements:
https://iov.atlassian.net/wiki/spaces/PRODUCT/pages/1081349/Mutable+product+fees+-+product+specification

In https://github.com/iov-one/weave/pull/992 (released as part of Weave 0.21.3) the message fees become mutable.

In IOV Core we should

- [x] Update codec to 0.21.3
- [x] Update local bnsd chain to 0.21.3
- [x] Update local test genesis to set an `app_state.conf.msgfee.fee_admin` and `.owner` (see https://github.com/iov-one/weave/pull/992/files#diff-af7902b005c880ea7df3443289f25ea0R26-R29). This should be the economic committee
- [x] Implement encode/decode of transactions with [SetMsgFeeMsg](https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/v0.21.3/docs/proto/index.html#msgfee.SetMsgFeeMsg)
- [x] Create proposal type that allows supports `SetMsgFeeMsg` as an action
- [x] Write test that changes to configuration of the local chain via governance (we can only have one admin, so we need to choose between direct address or governance rule)

Note: right now deploying 0.21.3 to IOV mainnet leads to a situation where we cannot access the new functionality since no `app_state.conf.msgfee.fee_admin` is set in mainnet genesis. This will be fixed one way or another. But IOV Core can implement and test the new functionality as long as it connects to newly spawned blockchains.

**Comment by willclarktech** [comment]
@webmaster128 Is it definitely `UpdateConfigurationMsg` we need to support, not `SetMsgFeeMsg` (or both)?

**Comment by webmaster128** [comment]
> Is it definitely `UpdateConfigurationMsg` we need to support, not `SetMsgFeeMsg` (or both)?

It is not, my fault. My thinking was that it is `UpdateConfigurationMsg` because in the `cash` module, the fee (`minimal_fee`) is part of the [Configuration](https://htmlpreview.github.io/?https://github.com/iov-one/weave/blob/v0.21.3/docs/proto/index.html#cash.Configuration) object.

`SetMsgFeeMsg` is what we need. Configuration updates are not required at the moment.
