### ISSUE TITLE
Collect everything about chainID

### ISSUE THREAD

**Issue by annatorok** [iov-one/iov-core#1290]

**Comment by webmaster128** [comment]
Quoting my Slack message from 2019-11-14:

> Regarding chain IDs:
> - we need to extend https://github.com/iov-one/iov-core/blob/master/docs/chain-ids.md to other chains, with a priority (1) on Cosmos hub and priority (2) chains in the cosmos ecosystem
> - The two main challenges are: (a) the chain ID in a Tendermint geneses file can be an aritrary length unicode string, including all kind of special characters and (b) Cosmos Hub tends to launch new chains from time to time. For both issues there exist no fixed solution. Potential solutions are (a) have two prefixes, one that takes the chain ID directly and one that hashes the chain ID it it is too long or contains non-whitelisted characters and for (b) acknowledge the fact that those are different blockchains and build a client-side solution that knows that cosmoshub-3 is a successor/fork of cosmoshub-2
> - In https://github.com/UCRegistry/registry, chain IDs are needed as part of the registry, but there is no consensus how to specify them in a strict manner for anything else than Ethereum chains
> - https://github.com/ChainAgnostic/CAIPs/pull/1 is the most promising discussion towards a solution
> That’s all I know right now
