### ISSUE TITLE
Make sure Neuma extension works even if any particular node is down

### ISSUE THREAD

**Issue by annatorok** [iov-one/iov-core#1294]
We should make sure that the Neuma extension is working even if a node is down. Currently, if a node is down (eg. Lisk), the users cannot log in to Neuma and the application will throw an error.

Can this be done only on front-end side somehow?

When loading a chain -> if it's down, don't load that chain but continue to load the other chains that are available - in the UI probably we should be display the change that that chain is not available (eg. we cannot display the balance in that case because we don't have that information or if the IOV name service chain is down, we cannot show the starnames)

- [x] pinpoint the line of code that fires the network error
- [x] if a node is down, the extension is still working and users can sign up or unlock the extension
- [x] when a node is down, we should display that with a red dot instead of a green one
- [x] when a node is down and the user signs up or unlocks the extension, it should say "Unable to connect to < name of the blockchain >. This should be only a warning message, the user would be able to use the extension and be navigated to the main screen
- [x] if a node is down and the user is signed in to the extension, that node's information is not available, so we shouldn't show eg. balance (that chain's currency) in the extension

![Menu - Networks (1)](https://user-images.githubusercontent.com/7419692/71961206-2a9f7d80-31f7-11ea-88e9-b6a83895b0eb.png)

**Comment by willclarktech** [comment]
@annatorok How about transferring this issue to the front end repo?

**Comment by annatorok** [comment]
@willclarktech  We already have a ticket for this there (Abel is working on it currently), so that's why I closed it here.
