### ISSUE TITLE
Allow fee payer to be specified in BNS

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1299]
Registrars should be able to pay all costs for a user's starname registration and/or target update.

**Comment by webmaster128** [comment]
@willclarktech in which context is this needed? As far as I know, executing batch messages are only used for proposal executions. Do we need to decode those?

**Comment by willclarktech** [comment]
@webmaster128 See https://iov.atlassian.net/wiki/spaces/PRODUCT/pages/14221370/Batch+transactions
