### ISSUE TITLE
Prepare releasing IOV Core 2

### ISSUE THREAD

**Issue by annatorok** [iov-one/iov-core#1300]
Edit Simon:
The new requirement for IOV Core 2 environments should be native BigInteger support, introduced in TypeScript 3.2. See also https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#caveats-1 and see what this means for us.

For me it means

- [x] Cutting a 1.2.0 release (~after #1298 is merged~), creating a 1.2 release branch for patches of necessary
- [x] Writing a nice little CHANGELOG entry for 2.0.0 defining the new runtime environment requirements
- [x] Change CI configuration to use the lowest version of nodejs we support from now

The last point is what unblocks merging Cosmos codec

**Comment by willclarktech** [comment]
@webmaster128 Do we need to create the 1.2 release branch now or can we create it as/when necessary?

**Comment by webmaster128** [comment]
@willclarktech let's just do it to make `master` free for breaking changes. IOV CLI in nodejs 12 would be good to release soon.
