### ISSUE TITLE
Refactor `codec.bytesToSign` to accept an unsigned transaction without a creator

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#1314]
Follow-up to #1308 
This may directly involve replacing the `WithCreator` type with a `WithChainId` type.

**Comment by willclarktech** [comment]
Current state of things:
- BNS does not use the creator besides the chain ID
- Cosmos does not use the creator besides the chain ID
- Ethereum currently checks the creator's public key matches the sender's address but otherwise does not need the creator besides the chain ID
- Lisk requires the sender's public key, currently taken from the creator assuming they are one and the same

We have a choice here:
1. Keep the `creator` field and require codecs for all chains to accept it, even if most of them only need the chain ID part. In this case we might want more checks to confirm the creator and sender are the same account and might want to rename `creator` to something more descriptive like `senderIdentity`.
2. Replace the `creator` field with a `chainID` field which will live in the BCP type, and create a Lisk-specific transaction type which extends `SendTx`, adding a `senderPublicKey` field.
3. The same as 2 but instead of having an exception for Lisk change the type of the `sender` field to a public key in the BCP `SendTx` type, since the address can be calculated from it as needed.

**Comment by webmaster128** [comment]
I’d go for 1 in order to stick with the goal of unifying access to different blockchains.

3 does not work work for the reading part of things. When you get send transactions from and Ethereum scraper, you have sender addresses but not pubkeys.

**Comment by webmaster128** [comment]
The whole reason for the existence of `WithCreator` is that we don't get the pubkey of a send transaction from Etherscan. When `.creator` disappers, most likely `.chainId` can be part of every `LightTransaction` at to level.
