### ISSUE TITLE
Deprecate @iov/testing

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1358]
This temporary package name was never really used.

For some strange reason, `npm deprecate @iov/testing "Unmaintained. This was renamed to @iov/utils."` succeeds without any output but has no effect. No deprecation is stored on npm. See `npm view @iov/testing` or https://www.npmjs.com/package/@iov/testing

**Comment by willclarktech** [comment]
I managed to do this by specifying the version number: `npm deprecate @iov/testing@2.0.0-alpha.3 "Unmaintained. This was renamed to @iov/utils."` Possibly the initial `@` was confusing npm?
