### ISSUE TITLE
Release final version of IOV Core 2.0.0

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#1359]
Everthing is done from my side and this is ready to be released. It just needs a tag and be published to npm.

**Comment by willclarktech** [comment]
Checklist before publishing:
- [ ] Update `@iov/cosmos` dependency to `@tendermint/amino-js@0.7.0` when released.
- [ ] Update `@iov/cosmos` CAIP5 implementation once the changes are finalised ([here](https://github.com/ChainAgnostic/CAIPs/pull/9)).
