### ISSUE TITLE
Add CI tests on Windows (node + Edge)

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#158]
#42 is basically done, we will need windows support sometime, but this is not done so well in Travis, so let's pull this out to a later long-term issue.

**Comment by webmaster128** [comment]
AppVeyor runs on Windows Server 2016, that do not support Edge. We need a CI service with Windows 10 machines

**Comment by webmaster128** [comment]
Visual Studio Team Services provides hosted Windows agents but non of the available images contains Edge: https://docs.microsoft.com/de-de/vsts/pipelines/agents/hosted?view=vsts#software

**Comment by webmaster128** [comment]
Build system and nodejs on Windows is now tested using AppVeyor. Testing the Edge browser needs to be done locally at the moment

**Comment by ethanfrey** [comment]
`"test-edge": "yarn pack-web && karma start --single-run --browsers Edge",`

Nice... I would say this is good enough for now.
Node on windows in the CI avoids a lot of file path issues.
And being able to locally debug any edge issues with a simple `yarn test-edge` is a good solution.

I will consider this done
