### ISSUE TITLE
Expose API to iov-wallet (in process)

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#162]
We need to deprecate weave-js and have the iov-wallet team use web4. To do so, they need to reproduce the current functionality with the new library.

- [x] Review iov-wallet code to see what they need
- [x] Meet with iov-wallet team to coordinate on the effort
- [x] Implement missing endpoints (wrappers over our functionality)
- [x] Integrate on a branch of iov-wallet
- [x] Package and release (0.0.1? 0.1.0?) so they can use this code externally

**Comment by webmaster128** [comment]
Done :)
