### ISSUE TITLE
Open source repository

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#176]
- [x] Reach 1000 commit goal :tada:
- [x] Review dependencies (https://github.com/iov-one/web4/issues/186)
- [x] Change license to Apache 2
- [x] ~Clear commit history to avoid publishing earlier software states as AGPL-3.0?~
- [x] Review licenses of dependencies `yarn licenses list`
- [x] Finalize name of the library (see #208 )
- [x] ~Commit build dirs to source control~
- [x] Set up .npmignore files on all repos
- [x] Claim @iov name on npm (or other if taken)
- [x] Figure out how to publish lerna packages
- [x] Verify we can import and build code in other repo (eg. iov-wallet)
- [x] Add README to the repo for devs
- [x] Add README to each sub-package for npm (with basic explanation of main entry point)
- [x] ~(once we are satisfied it works) Set version to 0.1.0 on all packages and tag repo~
- [x] Remove currently uploaded releases https://github.com/iov-one/iov-core/releases for licensing reasons

**Comment by webmaster128** [comment]
Repo is open source now. NPM release is waiting for #244

**Comment by webmaster128** [comment]
Lerna takes care of all the tagging for us. 0.2.0 would be the next version and the first to be published on npm

**Comment by webmaster128** [comment]
We got a pre-release version of 0.2.0 on npm: https://www.npmjs.com/package/@iov/core

All out packages are there now. I tested @iov/cli which does not work for several reasons (i.e. don#t waste time tying it). Maybe someone can try @iov/core or the most simple case @iov/encoding.

Releasing works as described here: https://github.com/iov-one/iov-core/wiki/Publishing#how-to-publish-to-npm

**Comment by ethanfrey** [comment]
I tried the following....

On a new directory, `yarn init` , `yarn add @iov/core`

Then added index.js:

```
const { Bip39, Random } = require('@iov/crypto');
const { Ed25519SimpleAddressKeyringEntry, UserProfile} = require('@iov/keycontrol');
const { Encoding } = require('@iov/encoding');
const { fromHex, toHex } = Encoding;

const demo = async () => {
    // 16 bytes -> 12 word phrase
    const entropy16 = await Random.getBytes(16);
    const mnemonic12 = Bip39.encode(entropy16).asString();
    console.log(mnemonic12);

    const profile = new UserProfile();
    profile.addEntry(Ed25519SimpleAddressKeyringEntry.fromMnemonic(mnemonic12));

    const sub = profile.entryLabels.updates.subscribe({ next: x => console.log(x) });
    profile.setEntryLabel(0, "12 words");

    const id1a = await profile.createIdentity(0);
    console.log(id1a.pubkey.algo, toHex(id1a.pubkey.data))
}

demo();
```

`node index.js`:

```
like claim lottery common garage taxi sentence minimum salute guess student prison
[ undefined ]
[ '12 words' ]
ed25519 99a5daaff8903c0c29a7a6bbe0cb6cad7957ffee18406d6c1d316be2e691fb09
```

(of course the actual words are different every time)

**Comment by ethanfrey** [comment]
What is the issue with @iov/cli?

**Comment by ethanfrey** [comment]
Looks good to me!
