### ISSUE TITLE
Implement LedgerSimpleAddressKeyringEntry.canSign

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#218]
as discussed in https://github.com/iov-one/web4/pull/214

**Comment by webmaster128** [comment]
Library user requests an interface like: "ledger disconnected / connected outside app / connected inside iovsign1 app" tristate indicator

So we could have some state

```ts
enum LedgerState {
    Disconnected,
    Connected,
    IovSignOpen,
}
```

and define `canSign = state === LedgerState.IovSignOpen`

**Comment by rudi-cilibrasi** [comment]
another set of names and a bit about interface on https://github.com/iov-one/iov-core/issues/271
feel free to combine and close all but one
