### ISSUE TITLE
Provide client/server bridge for iov-write

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#222]
If we wish to store the keys outside of the webpage, we need to call it somehow. The first step is to expose the entire API but then serialize it and send it over a pipe request/response style to a server that can handle this.

This could be over websocket, or message passing between webpage and chrome extension (this should be able to be passed in as the communication pipe).

Note, that this contains no authentication info per connection, allowing full access, that can be dealt with other issues. Also, this would require the entire web4 api to be async as messages return promises, so maybe we would introduce a bridge class (thanks rudi for the term) that could call either remote or local backend. easy enough to wrap sync functions in async.

**Comment by webmaster128** [comment]
Done by the implementation of an RPC signing server
