### ISSUE TITLE
Sample authentication wrapper over coreWriter

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#223]
With #222 we can call the web4writer api from possibly untrusted code. We would then want to require user confirmation to authorize steps here.

One approach to be discussed in this issue, is to wrap coreWriter interface (bridge) with  a layer that will intercept the calls, make some ui display to the user, and pass on to the underlying implementation on confirmation or return error if rejected.

Does this make sense? Is there another approach? Please to discuss here

**Comment by webmaster128** [comment]
API is not called from untrusted code directly. Instead a simple RPC interface serves as an interface where one specific communication is possible.
