### ISSUE TITLE
getNonce fails if there is no outgoing tx on the chain

### ISSUE THREAD

**Issue by Isabello** [iov-one/iov-core#230]
The logic in the code is flawed, as if nonce is undefined, the eval will fail and throws.

Error:
```
TypeError: Cannot read property 'nonce' of undefined
```

https://github.com/iov-one/web4/blob/b07ddbc/packages/iov-web4/src/web4write.ts#L53
```
  public async getNonce(chainId: ChainId, addr: Address): Promise<Nonce> {
    const nonce = await this.mustGet(chainId).client.getNonce({ address: addr });
    return nonce.data.length === 0 ? (Long.fromInt(0) as Nonce) : nonce.data[0].nonce; #### This line is the failure, we can't return nonce.data[0].nonce ####
  }
```

**Comment by ethanfrey** [comment]
This never really got fixed, but I also heard nothing about it again.
I will close it unless I can get a way to reproduce it
