### ISSUE TITLE
Build and publish docs in CI

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#233]
Since we do not want to store api docs in the repo (too big, change too often), we should create a nice place to host them.

For the beginning, we can request devs to generate locally, but this is a pain point and barrier to entry, which we want to make as easy as possible for anyone looking to build in the iov ecosytem.

`yarn docs` in the main package will build them all, we need to think of a hosting strategy, and then link them from the READMEs, so all npm packages have a link to current docs (on master? last tag??)

**Comment by webmaster128** [comment]
Not perfectly automated yet but the core of this issue is done. This is how you publish a docs update: https://github.com/iov-one/iov-core/wiki/Publishing
