### ISSUE TITLE
@iov/cli should install binary (work outside of monorepo)

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#248]
To make the tool more useful, we want to be able to do something like:

```
yarn add -D @iov/cli
// OR npm install -g @iov/cli
iov-cli // or other name
```

and that would launch the repl, complete with init script..

It seems that the cli only works inside the package in the monorepo, when called via `yarn cli`

**Comment by webmaster128** [comment]
For this to work wee need to specify a binary:

https://docs.npmjs.com/files/package.json#bin

This could be a shell script, that does the same thing as `"cli": "echo '\\nTo get started type: .load init\\n' && NODE_NO_WARNINGS=1 ts-node"`. However, the local ts-node is not available in a shell script. However, `"$(yarn bin)/ts-node"` could work.

**Comment by webmaster128** [comment]
If this should work on Windows without bash, we need to implement the shell script in .js …
