### ISSUE TITLE
export more @iov/ledger-bns package symbols to support highly interactive applications

### ISSUE THREAD

**Issue by rudi-cilibrasi** [iov-one/iov-core#271]
we would like to have a tristate indication such as:

LEDGER_DISCONNECTED or
LEDGER_CONNECTED or
LEDGER_IOV_APP  (if user is inside IOV wallet app)

a simply async await polling function that gets the current status and a recurrent change observer or subscriber type approach seems like one easy way to supply the required information.

**Comment by webmaster128** [comment]
Closing as this is a subtask of #218
