### ISSUE TITLE
Add secp256k1 keyring entry

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#294]
Ideally two classes to mirror `Ed25519HdKeyringEntry` and `Ed25519SimpleAddressKeyringEntry` from `iov-keycontrol/src/keyring-entries`.

I think secp support can be included directly in keycontrol and not as a external plugin (like ledger), as the implementation code is all in `@iov/crypto` which we already import.

This is a requirement to allow `iov-core` to work with ethereum based chains as well as the cosmos hub.

**Comment by webmaster128** [comment]
We can easily generalize Ed25519HdKeyringEntry to Slip10KeyringEntry, allowing derived classes to use both curves. I think this should be step 1 for this ticket

**Comment by webmaster128** [comment]
I am working on https://github.com/iov-one/iov-core/issues/294#issuecomment-416971109 now

**Comment by ethanfrey** [comment]
Sounds good. That is also where we want to do, support multiple algorithms in one keyring
