### ISSUE TITLE
web4 library stable

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#3]
Get the web4 library stable, no UI yet, but all APIs implemented.
This is a milestone and tracks a number of other issues

- [ ] KeyBase Controller / encrypted storage
- [ ] KeyRing ed25519 simple
- [ ] KeyRing ed25519 hd
- [ ] Tx Registry (per chain)
- [ ] BCPDemo buildTx function
- [ ] Tendermint-trust client
- [ ] BCP client
- [ ] web4 private API
- [ ] web4 public API
- [ ] ts-repl bindings for developer cli (use both public/private)
- [ ] TESTS!

**Comment by lazaridiscom** [comment]
@ethanfrey , just curious: may I ask why you don't use the https://github.com/iov-one/iov-core/milestone/1 for tracking?

**Comment by ethanfrey** [comment]
Cuz I made than a long time ago and forgot about it....

**Comment by ethanfrey** [comment]
We have a project board to track cross-project work, but I don't know if it is public

**Comment by ethanfrey** [comment]
The main dev is on vacation for a bit, when he comes up, I'll work with him to reboot with a public task board. There was not so much outside interest until now, but you are right, it is nice visibility.
