### ISSUE TITLE
Better handling of paths in HD keyrings

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#302]
Right now, the main keyring we use is `Ed25519SimpleAddressKeyringEntry` which hardcodes the beginning of a path and just increments the last value to produce multiple addresses. A `KeyringEntry` has just one command to create a new key, which accepts no arguments.

```
export interface KeyringEntry {
...
  // createIdentity will create one new identity
  readonly createIdentity: () => Promise<LocalIdentity>;
...
}
```

This is exposed in the `UserProfile` as:

```
  // creates an identity in the n-th keyring entry of the primary keyring
  public async createIdentity(n: number): Promise<LocalIdentity> {
    const entry = this.entryInPrimaryKeyring(n);
    return entry.createIdentity();
  }
```

This doesn't allow us to  specify the path to use for hd keys, or to import a private key from another key store. It also is not the cleanest way to specify the algorithm. I mean, n=0 could be ed25519 and n=1 secp256k1, but that is not so clear.

We should make it easy to either import existing private keys, or to do something like "Create a new secp256k1 key with path 44'/1'/2'/0/x where x is one higher that the last value you generated with that prefix".

Let's figure out the nicest API for the user, then work on implementing it. As all the pieces are there, it shouldn't be too much hard crypto work, just API polish.

**Comment by ethanfrey** [comment]
What are the types of keyring entries we would want to support??

* HD generation in software (given bip39 mneumonic)
* HD generation in hardware (requires connection, mneumonic never exposed)
* Import private keys from other software
* Socket connection to process implementing one of the above (eg. extension connect to gateway app using node-ledger)

All should support both ed25519 and secp256k1

**Comment by webmaster128** [comment]
In https://github.com/iov-one/iov-core/blob/master/docs/KeyBase.md#address-architecture we define two types of address schemes, the simple linear Simple Addresses and the 4-dimensional Bip-44-like Extended Addresses.

My last information was that arbitrary keypairs like in Ed25519KeyringEntry should not be supported.

Should we start by defining the use cases we want to support?

**Comment by Isabello** [comment]
From: https://github.com/iov-one/iov-core/blob/master/docs/KeyBase.md#complete-object-definition

We are missing an easy way to use BIP44/32 paths
```
 "PublicIdentities": [
          "PublicIdentity": {
            "address": "0x6806ea1d9b2eb59DAc7fdcdf28bf8d5a12AD84Bc",
            "label": "Wells Fargo",
            "publicKey": {
              "algo": ed25519,
              "data": "52b96095d265a93308fcf5cb9627085f029546be8b31eccb00bad386a92544d7"
            },
            "chain": {
              "chain": "ETH",
              "tickers": ["ETH","ANT"]
            },
            "path": {
              "root": "m",
              "purpose": "44'",
              "coinType": "60'", # Defined here: https://github.com/satoshilabs/slips/blob/master/slip-0044.md
              "account": "0'",
              "change": "0'",
              "addressIndex": "0"
            }
          }
        ]
```

**Comment by webmaster128** [comment]
The interface for a BIP44 will look entirely different from a BIP32 interface. One is 4 numeric types, one is an arbitrary path with mixed hardened and unhardened components. So we need to know what we want.

**Comment by Isabello** [comment]
I propose that we support both BIP44 and BIP32 interfaces as designed in the original specs.

We can accommodate this by providing functions for `createBIP44Identity` and `createBIP32Identity`

One issue remains, not all tokens use a change address, so this will need to be an optional parameter when creating an BIP44 Identity with a Path.

https://github.com/trezor/trezor-core/tree/master/docs/coins

**Comment by ethanfrey** [comment]
Hmmm... maybe two functions.... 

`createBip44Identity(coinType: Slip0010RawIndex, account: Slip0010RawIndex, change: Slip0010RawIndex, addressIndex: Slip0010RawIndex)`

`createBip32Identity(path: Slip0010RawIndex[])`

**Comment by ethanfrey** [comment]
And generating/incrementing the addressIndex should happen outside of the UserProfile/KeyringEntry?

I heard there was the requirement that it be *possible* to give a full path including the address_index.
But is it also not useful to implement a *next key* mode?

**Comment by Isabello** [comment]
I think it would be useful to be able to increment for an existing identity, rather than needing to initialize a whole new one every time.

**Comment by webmaster128** [comment]
> One issue remains, not all tokens use a change address, so this will need to be an optional parameter when creating an BIP44 Identity with a Path.
> 
> https://github.com/trezor/trezor-core/tree/master/docs/coins

The getPublicKey column is probably irrelevant. For Ed25519 you cannot derive a public key from another public key anyway. I think we only need to look at the getAddress/sign columns. All of them are BIP32 compatible and the ones with 5 components are BIP44 compatible.

**Comment by ethanfrey** [comment]
This would lead me back to an earlier proposal, which seemed to have been rejected on slack....

`createBip44Identity(coinType: Slip0010RawIndex, account: Slip0010RawIndex, change: Slip0010RawIndex, addressIndex: Slip0010RawIndex | undefined)`

If `addressIndex` is not provided, it will look for highest existing addressIndex with same `purpose/coinType/account/change` and then increment it by one to generate the new path.

If the chain deviates from bip44 by not using change, they must use the bip32 function.... `createBip32Identity(path: Slip0010RawIndex[])`. Question being if we want to support auto-increment there as well or  force them to handle it externally if they begin to deviate from the standard.

I know there were concerns with auto-incrementing. Please explain here.

**Comment by webmaster128** [comment]
> I know there were concerns with auto-incrementing. Please explain here.

It feels like a strange mix between user tells the library which path it should be and library manages paths for the user.

This brings us back the question of use cases: do we have control over those paths or do we need to support paths generated elsewhere.

**Comment by Isabello** [comment]
We have control over paths input into us, but in order to be flexible, we need to allow user specified paths to support end users wanting to use our crypto to do their work.

**Comment by webmaster128** [comment]
When I read discussions like https://github.com/trezor/trezor-core/issues/326 and check table https://github.com/trezor/trezor-core/tree/master/docs/coins, I wonder if the library should care about the paths at all. So instead of supporting different incompatible variations of BIP44, we can just offer BIP32 and the caller can use any path, no matter if it is

* `m/44'/0'/a'/y/i` (BIP44)
* `m/44'/43'/a'/0'/0'` (BIP44-like, but incompatible due to hardened components at position 4 and 5)
* `m/44'/134'/a'` (not BIP44 but (ab)using the BIP44 purpose)
* `m/4804438'/i'` (not BIP44 and not claiming to be)

this keeps all the strangeness outside of the library and all the correctness and hard work inside.

**Comment by ethanfrey** [comment]
> this keeps all the strangeness outside of the library and all the correctness and hard work inside.

Best criteria I have heard for library boundaries

**Comment by ethanfrey** [comment]
Thanks for the tip. Noted in response to other pr. That terminology guide is quite useful, given we looked at ethereum and metamask for inspiration with naming.

**Comment by webmaster128** [comment]
@lazaridiscom we don't not use the term "HD keyring" in our code (it just came up here in this title). In IOV-Core, a "keyring" is a collection of secret data that can be stored and loaded as one entity – just like the gnome-keyring on Ubuntu or Keychain on macOS. Such a keyring has `n >= 0` keyring entries, currently named *KeyringEntry. A keyring entry could for example be a mnemomic together with a bunch of BIP32 paths, a Bip32KeyringEntry. This entry could be renamed to "wallet" if it helps, e.g. _Bip32Wallet is a keyring entry_. I'm open to improvement here but as far as I can see, the current naming is okay and consistent.

Regarding the point of this issue: in #310 we created a private Slip10KeyringEntry that one of our uses wants to utilize. Right now, Ed25519SimpleAddressKeyringEntry is the only exported HD keyring entry.

We want to have two extra child classes of Slip10KeyringEntry exported:
- Ed25519HdKeyringEntry 
- Secp256k1HdKeyringEntry

Both should take a mnemonic and can have arbitrary derivation paths.

The only issue with this is that the [createIdentity()](https://github.com/iov-one/iov-core/blob/v0.5.4/packages/iov-keycontrol/src/keyring.ts#L155) interface needs to take an argument (the path) and we'll need to give up the idea of creating identities without parameters. In fact every entry type other than Ed25519SimpleAddressKeyringEntry takes or should take a parameter:

- `LiskKeyringEntry.createIdentity` takes a passphrase
- `Ed25519KeyringEntry.createIdentity` should take a keypair from external (which would allow e.g. libsodium keypair imports)
- `Slip10KeyringEntry.createIdentity` should take a path instead of throwing and having `.createIdentityWithPath`

This could be implemented similar to

```diff
@@ -152,7 +152,7 @@ export interface KeyringEntry {
   readonly setLabel: (label: string | undefined) => void;
 
   // createIdentity will create one new identity
-  readonly createIdentity: () => Promise<LocalIdentity>;
+  readonly createIdentity: (config: unknown) => Promise<LocalIdentity>;
 
   // Sets a local label associated with the public identity to be displayed in the UI.
   // To clear a label, set it to undefined
```

```ts
interface PathConfiguration {
  readonly path: ReadonlyArray<Slip10RawIndex>
}

public async createIdentity(config: unknown): Promise<LocalIdentity> {
  function isPathConfiguration(config: any): config is PathConfiguration {
    console.log(config);
    return true;
  }

  if (!isPathConfiguration(config)) {
    throw new Error("Got wrong configuration type");
  }
    
  // use config.path from config of type PathConfiguration
}
```

which fails to compile for `entry.createIdentity();` but not for `entry.createIdentity("foo");`. The exact argument type must be checked at runtime.

**Comment by ethanfrey** [comment]
Cool, just discovered the unknown type after googling based on this code sample.
Seems fair to me, but we should then define some clear expected types and define them, like `isHdPath`.

Maybe the arguments could all be sure to carry run-time type info, like:

```
{ path: [Slip10RawPath.normal(10),...]}
{ passphrase: "oxygen mneumonic secret to lisk kingdom" }
etc..
```

but i like the idea for updating the interface like this.
we just need to be careful to make it easy as possible to properly use unknown

**Comment by lazaridiscom** [comment]
> Keychain on macOS

"keychain" as a specific meaning in crypto (HD Wallet, kind of "the deterministic sequence of keys".

>  the current naming is okay and consistent.

It is not. But its your system, so be happy with "keyring".

**Comment by webmaster128** [comment]
I am referring to the macOS software [Keychain](https://en.wikipedia.org/wiki/Keychain_(software)) and don't understand what this has do with HD wallets. We're not using the term "keychain" anywhere.

> It is not

Could you please elaborate based on my explanation, what the problem with the term "keyring" is? When a wallet is the "seed / wallet" from https://cdn-images-1.medium.com/max/2000/1*wqZOiTmcCv0ZWocto9esLw.png, our keyring can handle multiple wallets. I don't see why it is a problem to call a collection of wallets a "keyring".

**Comment by lazaridiscom** [comment]
Sorry, me mentally busy with other tasks.

Re "keyring" just see somewhere in my comments, you should get the idea:

https://github.com/iov-one/iov-core/issues?utf8=%E2%9C%93&q=commenter%3Alazaridiscom

re "keychain",

https://medium.com/bitcraft/hd-wallets-explained-from-high-level-to-nuts-and-bolts-9a41545f5b0
https://cdn-images-1.medium.com/max/800/1*HEkkQoiewvJU_rZP8CK_ZA.png

the "chain" therein, is the "keychain"

"chain" is any way bad, better use "sequence".

Anyways, me out!

**Comment by ethanfrey** [comment]
Great quote in the hd-wallets link:

```
You might be wondering, “Why do we hold on to this node structure that is either irrelevant (these constructs don’t exist in other popular coins that utilize HD wallets) or unused (no one really uses the account functionality anymore)?” It’s because this is a derivation path that’s been formally agreed upon by the different crypto communities. This is significant because if I wanted to, I could create my own tree following any made up standard I want and create and sign valid transactions from the public/private keys. But could any other wallet ever regenerate that structure? What happens if my app goes off the market? The user’s money is locked into a completely arbitrary private/public key tree. Not the best situation to be in. Therefore, we hold on to these artifacts of the past because an extra derivation or two is a small price to pay for consensus.
```

I am all for keeping consensus and consistency with other crypto systems. The problem I think, is we are not sure what the "standard" names for these items are.

Searching for "crypto keychain" lead to: https://allthingsdecentral.com/collections/keychains
And "crypto keyring" lead to something on cisco vpn.
"Crypto wallet" does seem to be closer, but as in https://blockgeeks.com/cryptocurrency-safe/ it mixes up "hardware wallets" that just do the signing and key storage, with "software wallets" which are complete apps and check balances and post transactions to a blockchain node.

Clearly, we want to stick with something closer to the meaning of "hardware wallet" than the use here of "software wallet". "HD wallet" usually talks more about the keys, but is also labelled on the whole app.

Looking back at https://github.com/iov-one/iov-core/issues/301#issuecomment-417499552

I do understand the argument in favor of wallet. 
Vault seems interesting, but seems to refer more to offline storage.

**Comment by ethanfrey** [comment]
Hmmm... HSM seems more along the lines... https://www.vaultproject.io/intro/vs/hsm.html

"SecurityModule" (Hardware or Software)?

Or Key Management Systemts... https://en.wikipedia.org/wiki/Key_management#Key_management_system

"KeyManager"?

ugh... too late.. good night

**Comment by webmaster128** [comment]
With #369 done, we have those types of arguments for createIdentity():

1. In the non-HD Ed25519KeyringEntry: a `Ed25519Keypair`
2. In the non-HD secp256k1 keyring entry: a `Secp256k1Keypair` (future) 
3. In general HD keyring entries: a `ReadonlyArray<Slip10RawIndex>`
4. In Ed25519SimpleAddressKeyringEntry: [an index i](https://github.com/iov-one/iov-core/blob/master/docs/KeyBase.md#simple-address-derivation) of type `number`

so we could use a parameter`{ pubkey?: PublicKeyBundle, privkey: PrivateKeyBundle } | { path: ReadonlyArray<Slip10RawIndex> } | { index: number }`

**Comment by webmaster128** [comment]
I agree that "wallet" is a better name for "keyring entry" (which matches https://github.com/lazaridiscom/mm-vault/blob/master/dev/terminology.md)

I still did not hear an argument, why "keyring" is a problematic term for a collection of wallets. This is why I stick with "I'm open to improvement here but as far as I can see, the current naming is okay and consistent." However, one possible improvement would be `Keyring` -> `Vault`

**Comment by webmaster128** [comment]
When #424 is done, createIdentity can get the following signature

```
createIdentity: (options: number | ReadonlyArray<Slip10RawIndex> | Ed25519Keypair) => Promise<LocalIdentity>;
```

It may be safer than passing `options: unknown` but it requres importing all the possible types in every implementation. I tend to not like the idea that the `KeyringEntry` interface needs to have an exhaustive list of possible option types.

**Comment by ethanfrey** [comment]
1. why number? The other two make sense?

2. Isn't it possible to define a helper function (from same file as Keyring class) that is something like:

```
function ensureSlipPath(wrapped: (options: ReadonlyArray<Slip10RawIndex>) => Promise<LocalIdentity>) : (options: number | ReadonlyArray<Slip10RawIndex> | Ed25519Keypair) => Promise<LocalIdentity> {
  if (Array.isArray(options) && options[0] instanceof Slip10RawIndex) {
    return wrapped(options);
  } else {
    throw new Error("unexpected type");
  }
}
```

then classes can just wrap their function with the guard and not worry about the def (sure there needs to be a trick or two with bind in this constructor

**Comment by webmaster128** [comment]
Re

1. LedgerSimpleAddressKeyringEntry can only create simple address identities, which are defined by a numeric index
2. I don't see how this improves the situation. We can easily determine the argument type at run time and the concreate wallet/entry implementation throws when it got an argument it cannot work with. But the KeyringEntry **interface** describes a common set of functions that work for any wallet/entry. Strictly speaking, createIdentity cannot be part of this interface because there is no signature that all implementations support. Small hack is to claim interface compliance at compile time and break it at run time.

**Comment by ethanfrey** [comment]
> 1. LedgerSimpleAddressKeyringEntry can only create simple address identities, which are defined by a numeric index

fair enough, updating ledger firmware code to take arbitrary paths is current project for rudi. we don't block on it, but know number will go away soon.

> 2. I don't see how this improves the situation. 

Sure, I guess if we do runtime checks in any case, and throw on anything unexpected there is no reason to limit it for the implementation. I was thinking mainly for the caller, but if we expose a limited api to UserProfile (main external entrypoint) that removes my concern... 

I like it when my IDE complains when I type the wrong argument. I had import trouble with iov-keycontrol before you pushed to npm and realized the pain of not having the types always visible.
