### ISSUE TITLE
Run local faucet for @iov/faucet unit tests

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#303]
Unit tests for this package run against friendnet, which seem much more like integration tests. I would prefer to pull up a local faucet in docker container, like we run local blockchains for CI. This is not urgent, but would make CI more reliable once friendnet has traffic.

https://github.com/iov-one/iov-core/pull/300#discussion_r213334401

**Comment by webmaster128** [comment]
This is important for 2 reasons

* for every CI build, we use the faucet 8 times, burning a lot of tokens
* we're already having CI problems because of _Mismatch 257 != 258: Invalid sequence number_

**Comment by webmaster128** [comment]
Current draft is here: https://github.com/iov-one/iov-core/pull/312

Now I am blocked by creating the `pk` file (https://github.com/iov-one/tools/issues/74)

**Comment by webmaster128** [comment]
No further work will be put into the BovFaucet implemented in golang. We use the installation at https://faucet.friendnet-slow.iov.one/faucet until BovFaucet is removed in 0.9
