### ISSUE TITLE
create 2-3 lists for constructor or constuctor-like functions in iov-core library

### ISSUE THREAD

**Issue by rudi-cilibrasi** [iov-one/iov-core#318]
We beginners are confused by the many symbols in iov-core library.
We wonder which of all the symbols  (specifically constructors, but maybe other executable exports?)

a) is potentially a good starting point for a first call in the library to execute, (e.g. UserProfile)
b) is definitely not a good starting point for a first call in the library  (IovWriter)
c) is hard to simply categorize and so has an odd story (where use is trivial but possible perhaps without params etc)

Having all global methods that are constructors or constructor-like listed in one of these three lists will be valuable to refactor the redux store. it will help in designing the new attribute names and shape.

**Comment by ethanfrey** [comment]
Good point to help improve introductory docs.
