### ISSUE TITLE
Hide private members at API boundary

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#336]
We had this discussion before that the `private` keyword is only enforced by typescript compiler and has no effect on the compiled javascript. I suggested to wrap objects at the API boundary (@iov/core) so normal usages would not leak info.

After working on the current web-app, I see them using private variables quite a lot to access things that were not well-exposed in the current API. This may work as a temporary measure, while issues are raised to fix the API, but it seems that `private` is not respected at all in the js world.

For example, the ui shows the mneumonic seed of the keychain, read from the keychain.

This violates all of our desire to keep things secret. And I think at the least, we should wrap the KeyringEntries we store in a UserProfile. It is possible to hide the data in a closure so it is impossible to access in javascript, while maintaining the same functionality:

ts:
```
export interface StringData {
  getData: () => string;
};

// you can only read data, not change it
export class Stable implements StringData {
  private data: string;

  public getData(): string { return this.data}
}
```

abuse in js:
```
stable.data = 'some different value'
```

safe wrapper:
```
function secureStringData(orig: StringData): StringData {
  return {
    getData: () => orig.getData(),
  }
};

const unsafe = new Stable('foo');
const safe = secureStringData(unsafe);
// safe.data doesn't exist, nor safe.orig
```

**Comment by ethanfrey** [comment]
Good example of the problem:
* https://yakovfain.com/2015/06/30/the-private-in-typescript-is-kinda-private/

Some more ambitious examples (correct, but complex):
* https://medium.com/@SylvainPV/type-safety-in-javascript-using-es6-proxies-eee8fbbbd600
* https://github.com/sylvainpolletvillard/ObjectModel
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

Expressing this logic to the type systems:
* https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types (read down to `Proxy<T>`)

Using closures to hide data:
* https://lazamar.github.io/closures-private-variables-and-methods-in-javascript/
* https://www.sitepoint.com/using-closure-space-create-real-private-members-javascript/

**Comment by ethanfrey** [comment]
Maybe this is an extension to #304 but kind of the different side. While working out the types I would need to build a client (and thus should be exposed), I came up with something like this:

```ts
// Writer is a strict subset of IovWrtier
export interface Writer {
  readonly profile: UserProfile;
  readonly chainIds: () => ReadonlyArray<ChainId>;
  readonly reader: (chainId: ChainId) => IovReader;
  readonly addChain: (connector: ChainConnector) => Promise<void>;
  readonly keyToAddress: (chainId: ChainId, key: PublicKeyBundle) => Address;
  readonly signAndCommit: (
            tx: UnsignedTransaction,
            keyring: number | KeyringEntryId,
          ) => Promise<BcpTransactionResponse>;
};

// UserProfile is a cleaned version of keycontrol.UserProfile
export interface UserProfile {
  readonly createdAt: ReadonlyDate;

  // ideal case, get or watch entries and identities
  readonly entries: ValueAndUpdates<ReadonlyArray<KeyringInfo>>;
  readonly getIdentities: (id: number | KeyringEntryId) => ValueAndUpdates<ReadonlyArray<LocalIdentity>>;
 
  addEntry(entry: KeyringEntry): void;
  setEntryLabel(id: number | KeyringEntryId, label: string | undefined): void;

  // maybe addIdentity? The args also need some work to support paths, but that is other PR
  createIdentity(id: number | KeyringEntryId): Promise<LocalIdentity>;
  setIdentityLabel(id: number | KeyringEntryId, identity: LocalIdentityId, label: string | undefined): void;

  // storeIn(db: LevelUp<AbstractLevelDOWN<string, string>>, password: string): Promise<void>;
  // lock(): void;
  // readonly locked: ValueAndUpdates<boolean>;
}

// overview information on the keyring...
// include index here, as this is important for ordering, and info remains if results get sorted/mapped
// by different processing steps (eg. lookup by id, but we want to retain display order).
export interface KeyringInfo {
  id: string;
  index: number;
  label?: string;
  // other????
  identities: number;
}
```

These are the shapes I would wrap up with protective closures and then expose to the world.

**Comment by webmaster128** [comment]
Closing as all known caller projects are TypeScript, which avoids the accidental misuse. If you want, you can always access private data, so we don't get an strict security here.
