### ISSUE TITLE
Remove types directories from the repo

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#342]
In the JS world, there is a tendency to check-in distribution files into a repo.

Advantages:

* you can download a distribution file from github and copy it into your project
* you can npm install from a git URL
* the current state of the repo is what you upload to npm, no temporary files involved

Disadvantages:

* When shipping a distributions file that includes dependencies, it is very hard to comply to licenses since you need to keep track of and ship all dependencies' licenses
* Code and distribution files are out of sync most of the time
* Annoying "regenerate" commits pollute the git history
* Depending on the degree of bundling and minimization, small source changes can lead to huge changes in distribution files
* diffs (especially between two version tags) get very hard to review as most of the diff is distribution files
* Maintaining different branches with distribution files can never merge automatically

For those reasons we decided early to not check-in TS -> JS build output.

Using a monorepo, this lead to the issue that before building the entire monorepo, types of different packages are not available. For example, removing the types of @iov/encoding gives you an editor full of errors and "any" types when reviewing code in @iov/crypto:

![bildschirmfoto von 2018-09-19 10-49-16](https://user-images.githubusercontent.com/2603011/45742256-dafc0380-bbf9-11e8-88bf-f540a3b56c14.png)

This problem only exists for local dependencies, not for npm dependencies and is monorepo specific. Until now we worked around it by checking-in type definitions (which increase PR diffs and occasionally create build problems).

| Feature | no build files checked-in | .d.ts checked-in |  .d.ts and .js checked-in |
|------------|----------------|----------------|----------------|
| A. Types available for review, coding and building before full build | ✕ | ✓ | ✓ |
| B. Running tests before full build | ✕ | ✕ | ✓ |

A full build runs for 2:18 min on my machine, so it would bearable to require a build before any kind of work. If you assume that no work can be done without running tests, the full build step is mandatory anyway.

I leave it for discussion if feature A. is something we want to have.

**Comment by rudi-cilibrasi** [comment]
This is why we standardized on `.mjs` as theoretically it can cache / store safely deps and precompiled artifacts before linking. Our expectation is that `.mjs` should keep getting faster than regular `.js` as project size increases due to the increased strictness. The increased strictness from the extension configuration constraints from `.mjs` should allow compilers to jam with static types better than what is possible in other extensions.

**Comment by webmaster128** [comment]
The .mjs file extension is a way to differentiate between CommonJS modules and ES6 modules on a meta level. TypeScript currently builds CommonJS modules, as ES6 module support was not very great when I last checked. However, the question CommonJS/ES6 modules is entirely independent of this issue and everything I wrote applies to both types of JavaScript output.

**Comment by webmaster128** [comment]
The checked-in types have value as described above, and the disadvantages are

1. increase PR diffs 
2. occasionally create build problems

The 2. point can be solved by ensuring the ./types directory is only cleard and filled after a successful build. This is implemented by the `move-types` yarn script in all flat packages already. Packages with subdirectories need to get a `move-types` that can handle subdirectories. If that can be solved, only disadvantage 1 is left, which I can live with.
