### ISSUE TITLE
Rename Algorithm enum cases to PascalCase

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#368]
```
enum Algorithm {
    ED25519 = "ed25519",
    SECP256K1 = "secp256k1"
}
```

should be

```
enum Algorithm {
    Ed25519 = "ed25519",
    Secp256k1 = "secp256k1"
}
```

for consistency

**Comment by webmaster128** [comment]
Probably non of our users is using the symbols `Algorithm.ED25519` and  `Algorithm.SECP256K1` directly. However, the type is exported via @iov/tendermint-types, so this should be considered a breaking change. Thus we don't include it in 0.6.x.

I just verified that Algorithm is the only enum left with SCREAM_CASE value names.

**Comment by lexcorp16** [comment]
Hi @webmaster128 I would like to take this up. Can you point me in the right direction

**Comment by webmaster128** [comment]
Hey @lexcorp16, you are very much welcome, thanks!

You can build this TypeScript project by running `yarn build` in the repo root. We use lerna to build all the sub-packages from there. The file to be changed is https://github.com/iov-one/iov-core/blob/master/packages/iov-tendermint-types/src/keys.ts. After that, all the places where we use Algorithm.ED25519 or  Algorithm.SECP256K1 must be updated. If you can build the whole project after the change, you are probably done.

**Comment by lexcorp16** [comment]
Thanks a lot @webmaster128 the PR is here https://github.com/iov-one/iov-core/pull/388
