### ISSUE TITLE
Add versioning to UserProfile serialization

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#374]
We already broke compatibility of UserProfile serialization 3 times and version 0.7.0 will be the 4th time. Every time such a break happens, user profiles stored with the older version cannot be opened using the newer version anymore. This is not dramatic during heavy development but we should try to increase stability now.  As a first step, we should introduce the concept of a serialization version at entry level as well as profile level. Having such versions, we can later decide if we want to provide an automatic migration or just throw an error.

**Comment by ethanfrey** [comment]
We don't have to break it.
I like the idea of storing `{version: x}` as part of the json objects
With v0.7.0 we can assume that all code without version is v0.6.0 and try to migrate from there... if needed, at least to validate migration.

Since v0.6.0 may be the first wallet anyone uses to save keys to disk besides doing development work and testing (eg. in a usable wallet), it may be good to try to transition easily and at least validate if we can.

**Comment by webmaster128** [comment]
Indeed, it could be done somehow. However, 0.6.0 -> 0.7.0 will probably be the greatest change in serialization ever. We are going to remove two keyring entry types entirely in order to create a more general one. Additionally 0.6.0 was built with no migration support in mind. Thus I doubt that it will be worth the effort to start migrations in 0.7.0.

**Comment by ethanfrey** [comment]
Fair enough. Then we plan 0.7.0 to migrate and can do a trial migration in some later release before public launch of the wallet

**Comment by webmaster128** [comment]
This has 4 layers that need versioning (from outer to inner)

- User profile storage (createdAt, keyring)
- Keyring storage (string encoding; encryption algorithms and parameters)
- Keyring serialization
- Keyring entry serialization

each of those layers can be updated independently and thus should have their own version.

**Comment by ethanfrey** [comment]
Was this done actually?
I had the odd feeling of seeing a PR that fixed it... but maybe that was just a dream....

**Comment by webmaster128** [comment]
it was a dream, nothing started yet
