### ISSUE TITLE
Common CI fails

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#392]
At the moment, we are experiencing some instabilities in our CI, which is annoying. Until now I always restarted builds but starting with this issue, I want to get an overview of the most common CI fails to help prioritize fixes. I link the failed builds in order to be able to gather additional information when needed.

## Client With HttpClient Can paginate over all txs

```
HeadlessChrome 0.0.0 (Linux 0.0.0) Client With HttpClient Can paginate over all txs FAILED
	Expected 2 to equal 3.
	    at <Jasmine>
	    at eval (webpack:///./build/client.spec.js?:159:31)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/client.spec.js?:4:58)
```

* https://travis-ci.com/iov-one/iov-core/jobs/149914988
* https://travis-ci.com/iov-one/iov-core/jobs/149929347
* https://travis-ci.com/iov-one/iov-core/jobs/150532345
* https://travis-ci.com/iov-one/iov-core/jobs/153463757
* https://travis-ci.com/iov-one/iov-core/jobs/156406268

## LiskConnection can get chain ID

```
Firefox 62.0.0 (Mac OS X 10.13.0) LiskConnection can get chain ID FAILED
	Error: Timeout - Async callback was not invoked within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL) in /Users/travis/build/iov-one/iov-core/node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 5100)
	<Jasmine>
```

* https://travis-ci.com/iov-one/iov-core/jobs/149918069

## LiskConnection can post transaction

```
HeadlessChrome 0.0.0 (Linux 0.0.0) LiskConnection can post transaction FAILED
	Expected undefined to be defined.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/liskconnection.spec.js?:133:40)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/liskconnection.spec.js?:4:58)
	Expected undefined to be greater than 6000000.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/liskconnection.spec.js?:134:40)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/liskconnection.spec.js?:4:58)
	Expected undefined to be less than 8000000.
	    at <Jasmine>
	    at Object.eval (webpack:///./build/liskconnection.spec.js?:135:40)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/liskconnection.spec.js?:4:58)
```

* https://travis-ci.com/iov-one/iov-core/jobs/149951799
* https://travis-ci.com/iov-one/iov-core/jobs/150949064
* https://travis-ci.com/iov-one/iov-core/jobs/151152521
* https://travis-ci.com/iov-one/iov-core/jobs/153793334

## LiskConnection Network error

```
LiskConnection can post transaction FAILED
	Error: Network Error (line 16)
	error properties: Object({ config: Object({ adapter: Function, transformRequest: Object({ 0: Function }), transformResponse: Object({ 0: Function }), timeout: 0, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, validateStatus: Function, headers: Object({ Accept: 'application/json, text/plain, */*' }), method: 'get', url: 'https://testnet.lisk.io/api/node/constants', data: undefined }), request: [object XMLHttpRequest], response: undefined })
	    at <Jasmine>
```

* https://travis-ci.com/iov-one/iov-core/jobs/154140220

## Tx (_long uppercase hex string here_) not found

```
HeadlessChrome 0.0.0 (Linux 0.0.0) Client With HttpClient Can query a tx properly FAILED
	Error: {"code":-32603,"message":"Internal error","data":"Tx (8D665E7E6C9CBD65F9EB5ED25CC938EC0688C002) not found"}
	    at Object.exports.ifError (webpack:///./build/common.js?:16:16)
	    at Object.exports.throwIfError (webpack:///./build/common.js?:7:29)
	    at HttpClient.eval (webpack:///./build/rpcclient.js?:78:29)
	    at <Jasmine>
	    at fulfilled (webpack:///./build/rpcclient.js?:4:58)
```

* https://travis-ci.com/iov-one/iov-core/jobs/150524298
* https://travis-ci.com/iov-one/iov-core/jobs/156594713
* https://travis-ci.com/iov-one/iov-core/jobs/157229078

## Rise node not available

```
RiseConnection : can get chain ID
   Error: Timeout - Async callback was not invoked within 15000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
```

* https://travis-ci.com/iov-one/iov-core/jobs/151788054
* https://travis-ci.com/iov-one/iov-core/jobs/151797930
* https://travis-ci.com/iov-one/iov-core/jobs/152024717
* https://ci.appveyor.com/project/webmaster128/iov-core/builds/19540179/job/07ogiiog3ntjapgs
* https://ci.appveyor.com/project/webmaster128/iov-core/builds/19544811/job/p5qvq5jmcend2lwr
* https://travis-ci.com/iov-one/iov-core/jobs/152061361
* https://ci.appveyor.com/project/webmaster128/iov-core/builds/19543948/job/egpjm4jnkv1mk3pu
* https://ci.appveyor.com/project/webmaster128/iov-core/builds/19606226/job/kfplvcp0wadsts6j
* https://travis-ci.com/iov-one/iov-core/jobs/152753650
* https://ci.appveyor.com/project/webmaster128/iov-core/builds/19632142/job/7dllfhq5xilb41wh
* https://travis-ci.com/iov-one/iov-core/jobs/152903728
* https://ci.appveyor.com/project/webmaster128/iov-core/builds/19637091/job/avlydhjwh8g8q0j0

## BovFaucet : can be used to credit a wallet

```
1. BovFaucet : can be used to credit a wallet
   Error: Error: Request failed with status code 500; response body: ""
       at faucet.credit.catch.error C:\projects\iov-core\packages\iov-faucets\src\bovfaucet.spec.ts:25:15
       at <Jasmine>
       at process._tickCallback internal/process/next_tick.js:189:7
```

* https://ci.appveyor.com/project/webmaster128/iov-core/builds/19513928/job/hckpkij7sluo5e0o

**Comment by ethanfrey** [comment]
The tx paginate issue only appears to be encountered in headless chrome, right?
Which is the only browser/karma test run against the blockchain, as other browsers are only tested on osx.

Maybe I should revisit the code there to ensure it is reentrant even in race conditions.

**Comment by ethanfrey** [comment]
The lisk issue...
Well, I would kind of like to remove any dependency on lisk testnet (or any non-local infrastructure) in our ci. Ideally we could launch a simple node like we do with tendermint. If not, maybe make those integration tests manual (not automatic on ci).

**Comment by webmaster128** [comment]
Looks like Rise testnet node is taking the lead recently. Let's work on this as soon as 0.7.0 is out

**Comment by webmaster128** [comment]
Some still exist but this is mostly out of date. Closing.
