### ISSUE TITLE
Connect to ethereum node and get chainId and height

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#402]
Beginning of implementation of a BcpConnection.

Feel free to use any libraries that are compatible with Apache license. If there is great code that is not, please discuss, maybe we more ethereum adapter to separate repo.

This story should include a test case that runs in CI against a local ethereum node. Please use https://github.com/trufflesuite/ganache-cli unless you have a really good alternative (I had good experience with the old version https://www.npmjs.com/package/ethereumjs-testrpc)

**Comment by LucasIsasmendi** [comment]
Why not following the same pattern as Lisk adapter an test directly against testnet? otherwise we will have several local demos running in the future, and we will need to provide a virtualbox or similar to have them all for a full local test

**Comment by Isabello** [comment]
Theres a wide variety of docker images available for ethereum

https://github.com/Kunstmaan/docker-ethereum
https://blog.pythian.com/deploying-private-geth-network-using-docker/
https://medium.com/@andrenit/buildind-an-ethereum-playground-with-docker-part-2-docker-image-928f8ceaac50
https://github.com/vertigobr/ethereum

**Comment by ethanfrey** [comment]
Are there any nice docker images to start up a local lisk testnet?
Cuz I think difficulty of setup was what drove Simon to use the real testnet

**Comment by webmaster128** [comment]
In addition to Ethan: you want tests to be deterministic and not depend on the data of a public blockchain. For example, we [test the balance of some address](https://github.com/iov-one/iov-core/blob/v0.6.1/packages/iov-lisk/src/liskconnection.spec.ts#L90) is 15.48687542 LSK. If you want to distract our work, just send money to that address and our CI is guaranteed to be red. With a code review of our test cases, one can easily denial of service our CI by changing different kinds of Lisk Testnet state.

**Comment by Isabello** [comment]
If needed i can help with lisk node CI, I built their entire CI architecture initially

**Comment by LucasIsasmendi** [comment]
the question is, are we going to support and maintain +20 docker images to run local tests when we have +20 blockchains added to iov-core? I want to think about scalability here, what is the best path

**Comment by Isabello** [comment]
we can look into tools that allow us to run tests only on sections of the code base that have changed. I know these exist but have never implemented one myself.

**Comment by LucasIsasmendi** [comment]
Imagine a desktop computer running +20 different blockchains locally at least, is that possible? what about 100?

**Comment by webmaster128** [comment]
It's a problem when it's a problem

**Comment by Isabello** [comment]
The point is, to make our tests deterministic we need to be able to run the tests against a fresh chain we have reliable control of.

Yes its possible to run that many, but nothing says the whole suite has to run at once and in parallel for a full test of all code pathways

**Comment by ethanfrey** [comment]
> Imagine a desktop computer running +20 different blockchains locally at least, is that possible? what about 100?

You can run any subset in a CI test. Each is it's own package and the tests are skipped with a flag.

If we have more than 3-4 blockchains, I think they all start to belong outside of the monorepo. In which case each repo just needs one docker file and one blockchain for the CI.

I would only run the bns chain for the `iov-bns` tests when working in that directory. It does make our CI slower when we run over all blockchains in node + browser but it is still at the limit of acceptable (and slowness more to tsc and karma than bns). Testnets are making it even slower. Solution would be to split into multiple repos at some point, especially non-core pieces that bring lots of dependencies and slow tests

**Comment by ethanfrey** [comment]
I can start up the chain locally in less than 10 seconds (and only so slow cuz there is a few second sleep in the script)

**Comment by petabytestorage** [comment]
It's very important to use ganache-cli aka testrpc.
