### ISSUE TITLE
Subscribe to new ethereum transactions

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#408]
Builds on #406 but provides the `subscribeTx`/`liveTx` functionality in addition to the `searchTx` method.

Unless etherscan implements this, we need to wait for later, as there is no general solution available.

**Comment by ethanfrey** [comment]
There are some documents related to subscriptions... https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#eth-subscribe

This definitely works with [block headers](https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-newblockheaders)

It also work for transactions, assuming we have log topics, we can [subscribe to new logs](https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-logs) as well [querying for past events](https://web3js.readthedocs.io/en/1.0/web3-eth.html#getpastlogs).

I think it would be good to investigate logs and topics a bit more to see if we can reproduce the etherscan functionality without middleware

**Comment by webmaster128** [comment]
events and logs do only exist for Smart contracts and cannot be used for ETH send transactions
