### ISSUE TITLE
Ensure ethereum connection compatible with MultiChainSigner

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#410]
Completing #402 - #409 should provide a complete implementation of the BcpConnection for ethereum, albeit only with the simplest transaction type.

Please validate by plugging this into IovWriter/MultiChainSigner and running a high level `signAndCommit` test to move ETH tokens.

(I think this is done, but maybe a few more tests or missing methods)

**Comment by webmaster128** [comment]
Closely related: https://github.com/iov-one/iov-core/issues/572

**Comment by ethanfrey** [comment]
Closing in favor of #572
