### ISSUE TITLE
Properly handle pending/unconfirmed/confirmed state on ethereum transactions

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#413]
Builds on #410 / #411 

Since block times are long and there is no instant finality, we need to mark transactions as `Pending | Unconfirmed | Confirmed`

* `Pending`: successfully reach a blockchain node and is "in mempool"
* `Unconfirmed`: successfully written in a block, but cannot yet guarantee it won't be reverted
* `Confirmed`: confident the transaction will not be reverted (block depth depends per chain)

This may require updates to the APIs (if not addressed earlier for lisk), and will require additions to the ethereum implementation.

**Comment by webmaster128** [comment]
We need that for Lisk and Rise as well. In the Faucet, I'd like to adapt balance checking based on the return value of `MultiChainSigner.signAndCommit`. Thus I suggest

```ts
export enum BcpTransactionState {
  /** accepted by a blockchain node and in mempool */
  Pending,
  /** successfully written in a block, but cannot yet guarantee it won't be reverted */
  Unconfirmed,
  /** confident the transaction will not be reverted (block depth depends per chain) */
  Confirmed,
}

export interface BcpTransactionResponse {
    readonly metadata: {
        readonly state: BcpTransactionState;
        /** only available for state .Unconfirmed and .Confirmed */
        readonly height?: number;
        /** Number of blocks above the transaction's block. Only available if height is available*/
        readonly confirmations?: number;
    };
    readonly data: {
        readonly message: string;
        readonly txid: TxId;
        readonly result: Uint8Array;
    };
}
```

**Comment by ethanfrey** [comment]
This sounds good. Two points.

One is we can make `/** only available for state .Unconfirmed and .Confirmed */` explicit:

```ts
export interface Metadata = 
  | { readonly state: BcpTransactionState.Pending}
  | { 
      readonly state: BcpTransactionState.Confirmed | BcpTransactionState.Confirmed;
      readonly height: number;
      readonly confirmations: number;
   }
```

**Comment by ethanfrey** [comment]
Second point is what our return value for `signAndCommit` is....

Current: 
` signAndCommit(tx: UnsignedTransaction, walletId: WalletId): Promise<BcpTransactionResponse>`

Proposed: 
` signAndCommit(tx: UnsignedTransaction, walletId: WalletId): Stream<BcpTransactionResponse>`

This means it would emit a Pending state upon mempool, Unconfirmed on first block (unless tendermint), a new Unconfirmed with on higher confirmation count on each successive block, and Confirmed when the count is high enough.

We could listen to that even and show the confirmations increase in a UI.

If so, we might want to show some helpers. Like....

```ts
function waitForConfirmation(stream Stream<BcpTransactionResponse): Promise<BcpTransactionResponse> {
  return new Promise((resolve, reject) => {
    stream.filter(resp => resp.metadata.state === BcpTransactionState.Confirmed).first().subscribe({
      next: x => resolve(x),
      error: err => reject(err),
    });
}
```

**Comment by webmaster128** [comment]
> One is we can make `/** only available for state .Unconfirmed and .Confirmed */` explicit:

I cannot stop dreaming about Swift again: with [associated enum values](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html#ID148) this is 

```swift
enum BcpTransactionState {
    case pending
    case unconfirmed(Int, Int)
    case cnconfirmed(Int, Int)
}
```

I think we should clarify the JSON compatibility requirements of BcpTransactionResponse or Bcp* in general.
