### ISSUE TITLE
Rename IovWriter to MultiChainSigner

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#416]
Closes #291 

- [x] Rename IovWriter to MultiChainSigner
- [x] rename the getter `reader(chainId: ChainId): BcpConnection` to `connection(chainId: ChainId): BcpConnection`

**Comment by webmaster128** [comment]
Added the other open renaming from #291 in here

**Comment by LucasIsasmendi** [comment]
IovWriter is in a writer file and assigned to const writer in multiple places, should I rename everything to signer or multichainSigner?
