### ISSUE TITLE
Update BNS codec for 0.9.0 support

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#493]
`@iov/bns` is still using the codec from weave and bcp-demo v0.6.0. These were merged in 0.7.0 and new extensions were added in 0.8.0 and 0.9.0. Luckily they have all been backwards compatible, so the older codec still produces binary transactions compatible with the newer blockchain, but we need to expose the newer features.

- [x] Update the protobuf generation scripts for single repo (moved to #504)
- [ ] Re-generate protobuf definitions
- [ ] Update wrappers in `@iov/bns` to refer to the new naming

The end result should expose the same features as now, but have access to the newer, fuller codec

**Comment by webmaster128** [comment]
Wrapper changes

1. Add memo to SwapCounterTx?
2. FullSignature.publicKey -> .pubkey
3. BcpNonce.publicKey -> .pubkey
