### ISSUE TITLE
Expose BNS transactions

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#494]
Depends on #493 

- [ ] Add transaction types for the bns registration for human value names and blockchain names, as well as updating the addresses associated with a value name.
- [ ] Implement these transactions in `@iov/bns`
- [ ] Consider defining subtypes for Signers based on which group of transactions they support (basic, atomic swap, name service, etc.)

**Comment by ethanfrey** [comment]
TODO: link to bns spec. link to implementation of messages (protobuf) for go code

**Comment by webmaster128** [comment]
Should this ticket be done running the bnsd:v0.8.0? Is there binary data available to test the decoding/encoding?

**Comment by ethanfrey** [comment]
Yes, test it against bnsd:v0.8.0

Easiest tests to write are running against server, but hard to debug.
I wrote some little go code wrappers to generate samples in the past. If you give me a list of objects (messages, tx, etc) that you wish to have locally to write non-blockchain tests against, I will generate some binary data files Tuesday.

This is like the binary/json data in testdata right now, just extended for more bns types.

**Comment by webmaster128** [comment]
I think I need

> TODO: link to bns spec. link to implementation of messages (protobuf) for go code

to continue here. I don't find the names of the transactions. I was searching in the neighbourhood of SetWalletNameMsg but did not find anything.

**Comment by ethanfrey** [comment]
For BNS spec, at least:

https://github.com/iov-one/bns-specblob/master/README.md
https://github.com/iov-one/bns-spec/blob/master/ValueNameSpace.md
https://github.com/iov-one/bns-spec/blob/master/PersonalizedAddress.md

Maybe @Isabello can add some more links
