### ISSUE TITLE
Add BNS query/watch support

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#495]
Depends on #493 

We should be able to query and watch the various bns data types.

- [ ] value name by name
- [ ] value name by (chain, address) - reverse lookup
- [ ] blockchain by chainId

After this and #494, a client should be able to register and query bns value names against a running bnsd 0.8.0/0.9.0 instance

**Comment by webmaster128** [comment]
> value name by name

Is "name" the deprecated name from `namecoin.SetWalletNameMsg`? Then I think we should drop that and query _value name by address_ instead.

**Comment by ethanfrey** [comment]
> Then I think we should drop that and query value name by BNS address instead.

We should query by username (first point)

Maybe there is a better word for it. In any case the id of the nft token

**Comment by webmaster128** [comment]
Thanks for clarification, makes sense now. We call it `username` in `RegisterUsernameTx` (which is implemented as the ID of the NFT)
