### ISSUE TITLE
Allow client to recover mnemonic from existing UserProfile

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#497]
To allow implementation of the wallet ux, we need to be able to display the mnemonic from an existing wallet, as most users care to write it down *after* they have funds inside.

We should expose an API call, so we can recover the menmonic from a KeyringEntry/UserProfile. This may (at dev discretion) require providing the proper password with which the KeyringEntry was saved. Seems more secure, but may just be a false sense of security with more complicated API.

**Comment by ethanfrey** [comment]
"Password protection" is a false sense of security according to @webmaster128 

Let's just add a getter.

**Comment by webmaster128** [comment]
MetaMask asks the user at application level for the password when trying to export the private secret information. Following this path, the secret is available
- encryted on disk
- plain in the process
The process takes care of all exports out of the process:
- process -> user: password required
- process -> disk: not supported

Now every other process of the same user needs the password to access the secret.

The process can mess up with the secret of course but this is something we cannot prevent anyway.

**Comment by webmaster128** [comment]
Done by #511
