### ISSUE TITLE
Deploy new iov-faucet to xerusnet and yaknet

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#498]

**Comment by webmaster128** [comment]
Depends on https://github.com/iov-one/iov-faucet/issues/12

**Comment by webmaster128** [comment]
Should be done by now. I will take over to ensure it is deployed on xerusnet and yaknet

**Comment by webmaster128** [comment]
Done by @husio

**Comment by ethanfrey** [comment]
🎉 thanks @husio
