### ISSUE TITLE
Split @iov/tendermint-types

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#514]
@iov/tendermint-types somehow became home of very generic types we use everywhere. But it should be possible to use IOV-Core without Tendermint-chains and without the term "tendermint" in packages.

In there we currently have

```
// keys
enum Algorithm
type PrivateKeyBytes
interface PrivateKeyBundle
type PublicKeyBytes
interface PublicKeyBundle

// network
type ChainId

// transactions
type SignatureBytes
interface SignatureBundle
type PostableBytes
type TxId
interface TxQuery
interface Tag
```

Tendermint types used by tendermint:

| Type name  | used in @iov/tendermint-rpc | used in @iov/bcp-types | used in @iov/bns |
| ------------- | ------------- | ------------- | ------------- |
| Algorithm  | ✅ | (implicitly in PublicKeyBundle) | ✅ |
| PrivateKeyBytes  | - | - |  ✅ |
| PrivateKeyBundle  | - | -  | ✅ |
| PublicKeyBytes | ✅ | (implicitly in PublicKeyBundle) | ✅ |
| PublicKeyBundle | ✅ | ✅ | ✅ |
| | | | |
| ChainId | ✅ | ✅ | ✅ |
| | | | |
| SignatureBytes | ✅ | ✅ | ✅ |
| SignatureBundle | ✅ | - | - |
| PostableBytes | ✅ | ✅ | ✅ |
| TxId | ✅ | ✅ | ✅ |
| TxQuery  | ✅ | ✅ | ✅ |
| Tag | ✅ | ✅ | ✅ |

Ideas for improvements:

1. `Tag` and `TxQuery` should be split to allow having different types in BcpConnection and in @iov/tendermint-rpc: `TendermintQueryTag` / `BcpQueryTag` and `TendermintTxQuery` / `BcpTxQuery`. 
2. `PrivateKeyBytes` and `PrivateKeyBundle` should move to @iov/bns and should not be exported as they are only used in bns codec tests
3. Make `SignatureBundle` available in @iov/tendermint-rcp only and rename to `VoteSignatureBundle`

The rest can go to a package called `@iov/base-types` for now.

**Comment by ethanfrey** [comment]
I think these were all bcp-types and you pulled them out, thus the name tendermint-types.

I am fine with 2 and 3.
I also like renaming this package or just rejoining what is left with iov-bcp-types for simplicity.

For #1 I tried to leave the query types pretty generic, and would like to only expose the BcpQueryTag, BcpTxQuery. The tendermint specific formatting should be in tendermint-rpc and can ideally even be un-exported, if the generic one provides enough power, to avoid people from making tendermint-specific queries.

The whole idea of tags needs to be thought through better as we are adding more chains. So, I would say this is the biggest part of non routine work.

**Comment by webmaster128** [comment]
>  I also like renaming this package or just rejoining what is left with iov-bcp-types for simplicity.

I want to keep @iov/tendermint-rpc indepenent of BCP to (A) avoid circular dependencies and (B) allow using @iov/tendermint-rpc for other applications. (B) is not a strict requirement but keeps thinks clean and disciplined.

> For #1 I tried to leave the query types pretty generic, and would like to only expose the BcpQueryTag, BcpTxQuery

Cool, this is my idea too.

> The tendermint specific formatting should be in tendermint-rpc and can ideally even be un-exported, if the generic one provides enough power, to avoid people from making tendermint-specific queries.

The question is which type @iov/tendermint-rpc expects. Since `buildTxQuery` lives in @iov/tendermint-rpc we need a `TendermintTxQuery` if we want to keep tendermint BCP-free.

The alternative is to move `buildTxQuery` into @iov/bns and and work on QueryString only, which is not so fancy I think.

Having compatible types `BcpQueryTag` / `TendermintQueryTag` as well as `BcpTxQuery` / `TendermintTxQuery` allows us to keep code unchanges now and be flexible to change the generic type or the implementation type in the future.

**Comment by ethanfrey** [comment]
> The alternative is to move buildTxQuery into @iov/bns and and work on QueryString only, which is not so fancy I think.

We can do that.
In fact, really understanding how to build these strings lives in bns anyway, all the logic in `iov-bns/src/tags.ts` is more complex than that one function to query. 

Tendermint could accept a query string and height range if you want to separate this more. Building the strings happens in bns already (needed domain knowledge), and the only consistent stuff that is tendermint-generic is the tx.height query elements.

**Comment by webmaster128** [comment]
Perfect, I try that. The only place we use `buildTxQuery` in tendermint-rpc is

```ts
  public static encodeSubscribe(req: requests.SubscribeRequest): JsonRpcRequest {
    const allTags: ReadonlyArray<requests.QueryTag> = [
      { key: "tm.event", value: req.query.type },
      ...(req.query.tags ? req.query.tags : []),
    ];

    const queryString = requests.buildTxQuery({ tags: allTags });
    return jsonRpcWith("subscribe", { query: queryString });
  }
```

which we can easily do by string concatenation I guess

**Comment by webmaster128** [comment]
I found a nice way to move `buildTxQuery(query: BcpTxQuery): QueryString` into @iov/bns and keep a simple `buildTagsQuery(tags: ReadonlyArray<QueryTag>): QueryString` for internal use in @iov/tendermint-rpc

**Comment by webmaster128** [comment]
Extracted https://github.com/iov-one/iov-core/issues/520, the rest is done. The result makes me very happy.
