### ISSUE TITLE
Let postTx in BNS resolve before block

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#564]
As discussed in https://github.com/iov-one/iov-core/pull/561#discussion_r236291870, it is more consistent to resolve postTx after sucessfully sending a transaction to mempool.

> watchTx based on hash will get an event when it is writen to a block.
> 
> If you subscribe before the commit, you will get notified when it is inside. Then you can listen to blockheaders to increment the confirmation.
> 
> This is just a change to the blocking call up to the first confirmation

This requires an additional

```ts
await response.blockInfo.waitFor(info => info.state === BcpTransactionState.InBlock);
```

for all code that expects the transaction to be in block (a lot of tests).

**Comment by ethanfrey** [comment]
Started another issue for it (oops), here was my other description that may have useful info:

Right now it blocks until a commit. Then is immediately confirmed.

We can use the tendermint broadcast_tx_sync to wait for it to make it into mempool, then return. And subscribe to the tx for notification when it is included in a block.

This will make the interface equivalent to other chains. In the UI, we assume that the initial promise is resolved quickly and then can continue to another page and subscribe to updates on it, adding a notification when processed. 1-2 seconds is not much, but is a very slow page load if we can avoid it.

Refering to this interface:

```
export interface BcpTransactionResponse {
  readonly blockInfo: ValueAndUpdates<BcpBlockInfo>;
...
