### ISSUE TITLE
Get block header from height

### ISSUE THREAD

**Issue by danZheng1993** [iov-one/iov-core#568]
To fetch the time information for transactions, need to fetch the block header which has same height as transaction.
Currently, there's no function available for this.

**Comment by Isabello** [comment]
I think you can use these functions exposed in the tendermint client

https://github.com/iov-one/iov-core/blob/706c87c037fb7b42f94ad700a4f6a99a29c066f1/packages/iov-tendermint-rpc/src/client.ts#L45-L53

**Comment by webmaster128** [comment]
@Isabello the problem is the tendermint client is not exposed (on purpose). I don't see a proper workaround here without creating ugly client code. This is just a missing interface we should expose in BCP.

**Comment by Isabello** [comment]
Oh ok. Understood then that its just a missing interface not missing feature from the library.

**Comment by webmaster128** [comment]
Done and released as 0.9.2
