### ISSUE TITLE
Reduce possible query types in BcpConnection.getNonce

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#573]
The interface now supports `BcpAddressQuery | BcpPubkeyQuery | BcpValueNameQuery` but we really only need `BcpAddressQuery | BcpPubkeyQuery`.

**Comment by ethanfrey** [comment]
Yes, this should also be part of a bigger refactor to stick all the value stuff in bns and not on each connection.

**Comment by ethanfrey** [comment]
We can do it now, ideally multisig signer will do this better

**Comment by webmaster128** [comment]
in #574, we consistently support `BcpAddressQuery | BcpPubkeyQuery` now. This ticket is an easy addition, but I did not want to blow up the other thing.
