### ISSUE TITLE
Define high-level rpc interface for out-of-process signer

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#575]
As discussed, we use a stateless protocol, either some rest/rpc type or fully asynchronous messages. (eg. send a push notification to a phone as request, get a message from long-polling a bridge server).

@webmaster128 can you link the presentation you made?

Also, look at https://docs.walletconnect.org/tech-spec for inspiration for connecting phone and desktop apps... It is ethereum-only, so I don't know if we can use any of the code, but at least look at the design for inspiration.

We need two main functionalities on the client side (beyond connecting)

* Request the current active identity (only if the user gives permission in the signer)
* Request the signer to sign a transaction (value name lookup, nonce lookup, and posting tx all occur in the signer. user must verify in the signer ui)

This replaces #397 although you can look there for some ideas as well.

Also, please take a look at #305 for some more half-finished ideas.

**Comment by webmaster128** [comment]
Some basic ideas exist but I don't want to finish this ticket without having a first implementation that shows if the overall interface makes sense.

Currently blocked by https://github.com/iov-one/iov-core/issues/621
