### ISSUE TITLE
Gracefully handle duplicate subscriptions in bns

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#581]
Currently, if I run `watchAccount` and `liveTx` on the same account, I will get an error from tendermint, as those both use the same subscription to monitor the transactions on tendermint.

Ideally, we could keep track of that client side, and the second call that wanted to use the subscription, could reuse the existing stream. So those two calls can work side by side.

Right now, this is forcing jumping a few hoops client side to watch them both

**Comment by webmaster128** [comment]
Good to know, thanks for sharing! The good thing to note is: this just found a bug where BNS subscribes to

```
  method: 'subscribe',
  params: { query: "tm.event='Tx'" }
```

twice for two different transactions because transaction hash gets lost on the way.

**Comment by webmaster128** [comment]
I can subscribe to both of those queries at the same time

```
tm.event='Tx' AND tx.height > 0
tx.height > 0 AND tm.event='Tx'
``` 

So tendermint must be doing a dump string comparison when throwing the _already subscribed_ error. This means we manage streams by query strings as a key.
