### ISSUE TITLE
Remove support for Tendermint 0.20/0.21

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#589]
All callers now use Tendermint 0.25.0+ networks. No need to compile unused code.

This maked Ripemd160 obsolete as well.

**Comment by ethanfrey** [comment]
On one hand I agree, and reducing a dependency is nice.
On the other hand, if we want a useful library, it is nice to support as many different versions of tendermint as people are actively using. 

I would hold off on this for a bit.
But maybe we would have eg. 0.25, 0.27, 1.0, 1.1 all supported eventually and should be able to support them until all sub 1.0 is fully deprecated. Upgrading is non-trivial and many projects (self included) stay a few versions behind.

**Comment by webmaster128** [comment]
> On the other hand, if we want a useful library, it is nice to support as many different versions of tendermint as people are actively using.

Jap, I agree and I'd leave the multi-version aproach untouched. Since we currently know no user that will need Tendermint 0.20/0.21 in IOV-Core 0.10.0, I think we can remove support for it. All future users will most likely start with a newer version of Tendermint, at least 0.25.0.
