### ISSUE TITLE
Implement watchBlockHeader for Lisk

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#599]

**Comment by willclarktech** [comment]
@webmaster128 Should this cover creating a client (ie probably HTTP to begin with) analogously to the Tendermint client?

**Comment by webmaster128** [comment]
I don't think an explicit client is necessary, as in contrast to Tendermint, there is only one HTTP API. In Tendermint we have a Client that abstracts the transfer layer (HTTP or WebSockets).

watchBlockHeader is part of a `LiskConnection`: https://github.com/iov-one/iov-core/blob/master/packages/iov-lisk/src/liskconnection.ts#L292-L294 In the method right above that you see how we access the Lisk API.

One could potentially create a Lisk API client to pull out the API access, but this has not been necessary so far.

**Comment by webmaster128** [comment]
Reduced the scope of this ticket to LISK only because we have no stable RISE test network to work with
