### ISSUE TITLE
Add tooling for bech32 <-> hex conversion

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#602]
It seems a bit tricky to add proper bech32 to the golang code, so let's just make it easy to interoperate on the client side....

Follow up on this comment https://github.com/iov-one/weave/issues/180#issuecomment-444062763 and add a small cli tool an/or a web tool to help with these conversions.

**Comment by webmaster128** [comment]
Done in https://github.com/iov-one/token-finder, deployed at https://iov-one.github.io/token-finder/
