### ISSUE TITLE
Simplify extending Transaction types

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#603]
Currently, we define `UnsignedTransaction` as a union type in `iov-bcp-types/src/transactions.ts`:

```ts
export type UnsignedTransaction =
  | AddAddressToUsernameTx
  | SendTx
  | SetNameTx
  | SwapOfferTx
  | SwapCounterTx
  | SwapClaimTx
  | SwapTimeoutTx
  | RegisterBlockchainTx
  | RegisterUsernameTx
  | RemoveAddressFromUsernameTx;
```

This means that every time we want to add a custom transaction for one blockchain (eg. bns), we must modify this core package. This is an annoyance for internal development, but a blocker for external development. I was contacted by a dev trying to use iov-core for a cosmos-sdk based blockchain and their main issue was adding custom transaction types.

The main usage of UnsignedTransaction is in signing:

```ts
/** A signable transaction knows how to serialize itself and how to store signatures */
export interface SignedTransaction<T extends UnsignedTransaction = UnsignedTransaction> {
  /** transaction is the user request */
  readonly transaction: T;

  readonly primarySignature: FullSignature;

  /** signatures can be appended as this is signed */
  readonly otherSignatures: ReadonlyArray<FullSignature>;
}

/** TxCodec knows how to convert Transactions to bytes for a given blockchain */
export interface TxCodec extends TxReadCodec {
  /** these are the bytes we create to add a signature */
  /** they often include nonce and chainID, but not other signatures */
  readonly bytesToSign: (tx: UnsignedTransaction, nonce: Nonce) => SigningJob;
  /** bytesToPost includes the raw transaction appended with the various signatures */
  readonly bytesToPost: (tx: SignedTransaction) => PostableBytes;
  /** identifier is usually some sort of hash of bytesToPost, chain-dependent */
  readonly identifier: (tx: SignedTransaction) => TransactionIdBytes;
}
```

Since many blockchains (eg. Lisk), only support a subset of the UnsignedTransaction types, it is not even providing us compile-time security.

I would propose the following adjustment to allow anything that is properly shaped to be used as a transaction:

```ts
export interface UnsignedTransaction extends BaseTx {
  readonly kind: string;
}
```

The generic transaction types should be in bns, also with corresponding guards:

```ts
function isSendTx(tx: UnsignedTransaction): tx is SendTx {
  return tx.kind === TransactionKind.Send
}

export type AtomicSwapTransaction =  |
  SwapOfferTx |
  SwapCounterTx |
  SwapClaimTx |
  SwapTimeoutTx;

function isAtomicSwapTx(tx: UnsignedTransaction): tx is AtomicSwapTransaction {
  return (tx.kind === TransactionKind.SwapOffer) ||
    (tx.kind === TransactionKind.SwapCounter) ||
    (tx.kind === TransactionKind.SwapClaim) ||
    (tx.kind === TransactionKind.SwapTimeout);
```

Extended blockchain-specific transactions, such as bns-specific ones, should be defined in that one package. bcp-types should only define shapes we expect to function over many blockchains.

In each package, when using the codec, the set of valid transactions (subset of `UnsignedTransaction`) should be enforced at runtime. eg.

```ts
  bytesToSign: (unsigned: UnsignedTransaction, nonce: Nonce): SigningJob => {
    if (!isSendTx(unsigned) && !isAtomicSwapTx(unsigned)) {
      throw new Error(`unsupported transction type: ${unsigned.kind}`);
     }
     // now, we know it is SendTx | AtomicSwapTx
     switch (unsigned.kind) {
       // ....
     }
  }
```

**Comment by webmaster128** [comment]
Yes, we should indeed decentralize Transaction type registration.

However, this makes a Lisk send transaction and a BNS send transaction two different things and [caller code for sending tokens](https://github.com/iov-one/iov-faucet/blob/v0.3.1/src/multichainhelpers.ts#L67-L80) cannot be chain-independent anymore. This could be solved by
1. codec functions that are responsible for creating common transactions (like send)
2. compatible interfaces (Lisk send and BNS send must have a compatible shape)

I'm not a fan of 2. as I'd like to add a codec specifier that acts a namespace:

```ts
export interface UnsignedTransaction extends BaseTx {
  readonly codec: string;
  readonly kind: string;
}
```

such that "lisk/send" and "bns/send" can be distinguished.

**Comment by ethanfrey** [comment]
> However, this makes a Lisk send transaction and a BNS send transaction two different things and caller code for sending tokens cannot be chain-independent anymore. This could be solved by

Yes, I agree this is an issue. We want:

1. All code that can come to a common abstraction to use a common abstraction (eg. SendTx, AtomicSwapTx)
2. All other transactions to use blockchain-specific interfaces

I would prefer not to distinguish "lisk/send" and "bns/send" as they can fit in a common interface. And when we can do that, we win a lot for interoperability and save client complexity. Otherwise, we are just a bunch of wrapper libraries.

In fact, I would say we focus on only `SendTx` and `AtomicSwapTx` (4 kinds) in bcp-types, and all the rest as chain-dependent. If we add functionality on multiple chains that can fit into a common abstraction, we can then later pull out an interface into bcp-types and enforce it.

What I do like from the `codec`/`kind` idea is allowing a two level namespacing.

I was thinking we would need, eg. `bns/vote` and `cosmos/vote` as different kinds... Maybe `codec` could be the package the interface is defined in `bcp`, `bns`, `lisk`, `dpos`, .... and the kind just has to be unique within the package.

Or we could use string concatenation to define the enum in each package. (`bcp/vote`). Both are fine with me. I think string concatenation for the constants to be easier somehow, but I am flexible.

I dislike splitting the original interfaces that belonged to bcp
