### ISSUE TITLE
Add pubkey to getAccount result

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#616]
it should be possible to get a pubkey from an address

**Comment by ethanfrey** [comment]
Well, if they have signed one transaction before, it is possible on all chains I know of. If they haven't signed anything, it is impossible.

I support an optional field, but let's consider where to place this. This did belong to BcpNonce before, as we had separated the queries for account balances and signing information (nonce, pubkey, etc).

If we add this as an optional field to Account, then I would suggest merging the last nonce query into Account as well and just have one object there with all info.

**Comment by webmaster128** [comment]
Good point about pubkey being optional.

I'd not mix this with nonce, because getAccount is always a network request but getNonce may be implemented locally.

**Comment by webmaster128** [comment]
Not possible on Ethereum because no pubkeys are stored
