### ISSUE TITLE
Add chainId to PublicIdentity

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#621]
A cryptographic keypair should be bound to one specific chain to avoid replay attacks. Also it should be easy to convert a PublicIdentity to an address, which requires the knowledge of the chainId.

- Add `chainId` parameter to `Wallet.createIdentity`
- Add `chainId` to `PublicIdentity`
- Remove redundant `chainId` parameter from `Wallet.createTransactionSignature`
- Convert `MultiChainSigner.keyToAddress` into `identityToAddress(identity: PublicIdentity): Address`
- Convert `TxReadCodec.keyToAddress` into `identityToAddress(identity: PublicIdentity): Address`

**Comment by ethanfrey** [comment]
In general, I like the idea, but I have some issues with it as well, and think it needs a deeper design review.

1. The Wallet interface allows a number of derivation schemes, including importing raw keys. This is also exposed (indirectly) in the UserProfile. The approach posted by Isabella had a derivation path as a mandatory field, which would make issues here.
2. The selection of path for hd wallets happens outside of UserProfile in the client library. If we want to do this properly, we will need to use chain-specific derivations for each chain, which must be passed into the Wallet/UserProfile. At least a way to iterate over all possible derivations until we find one not yet used.
3. This then constrains the usage of the wallet beyond the generic functionality we currently provide. I think this makes the API quite opinionated, which is both good and bad.

I would propose a more comprehensive design and review of any new proposal.

And I would propose to use a new class (not UserProfile). Either wrap UserProfile, or have a ChainAwareProfile class that can be quite opinionated and provide a specific API. Note the faucet uses a different derivation path than the wallet for the same chain... this is a nice design, but would be impossible if we have a very opinionate profile. That said, I would support such an opinionated profile to be the standard export for anyone wanting to do user-facing key management, and have the more flexible/complex api for scripts and daemons and such

**Comment by ethanfrey** [comment]
In such a case, we could gladly use `PublicKeyBundle`, `LocalKeyBundle` (with optional name attached) in the existing `UserProfile` and use the `*Identity` names for the new key manager.

**Comment by webmaster128** [comment]
Regarding

1. Right, I would not restrict any of the current options and also not include the derivation path as part of the PublicIdentity. PublicIdentity just becomes

```ts
/** a public key we can identify with on a blockchain */
export interface PublicIdentity {
  readonly chainId: ChainId;
  readonly pubkey: PublicKeyBundle;
}
```

So it ends up as a (chain, keypair) pair and caller software can generate the keypair however it wants.

2. "The selection of path for hd wallets happens outside of UserProfile in the client library." This remains unchanged. But now instead of just passing a HD path (including coin component), the caller software passes a chain ID along with that.

3. I don't think it does. A caller software can still user any combination of chain ID and keypair/HD path even the ones that make no sense. You can use a path `m/44'/234'/0` (IOV coin) on a Lisk chain ID if you want. Interpreting chain IDs and BIPP44 paths is out of scope for the Wallet level. So the only restriction we are really adding is: _when creating an identity, you set the chain ID it belongs to_. If you want to use a keypair on multiple chains, just create multiple identities.

Given that  _when creating an identity, you set the chain ID it belongs to_ is the only restriction we're adding, I don't think we need a different class for that.

**Comment by ethanfrey** [comment]
Okay, you just add that info inline. We can do it, but only in the scope of a larger design change, as I see this API becoming unweildly.

From a client (eg. wallet app), I show the user multiple "Accounts" (TODO: we need to find a better name), each of which supports multiple chains. Broken down to something like this:

* I want to create one "Account", this account may consist of `k PublicIdentities` spread over multiple chains (that I pass in the constructor? the creator?).
* I want to add more "Accounts", these other "Accounts" should all support the same k chains, and use the same chain-specific derivation paths
* I want to add support for a new chain, once I already have N "Accounts", this should create a new `PublicIndentity` for each existing "Account", to add support for the new chain.
* I want to find all `PublicIdentites` associated with a given (active) "Account", so I can query all their balances (and potentially use them to sign a tx).
* (less common) I want to find all `PublicIdentities` associated with a given chain, so I can validate my aggregate activity on that one chain.

I think these are basic requirements for usability one we add a second dimension. Right now, we select one PublicIdentity (one dimension id) and use that for querying all chains.

**Comment by ethanfrey** [comment]
Here is current public API for `UserProfile`:

```ts
export declare class UserProfile {
    static loadFrom(db: LevelUp<AbstractLevelDOWN<string, string>>, password: string): Promise<UserProfile>;
    readonly createdAt: ReadonlyDate;
    readonly locked: ValueAndUpdates<boolean>;
    readonly wallets: ValueAndUpdates<ReadonlyArray<WalletInfo>>;
    constructor(options?: UserProfileOptions);
    storeIn(db: LevelUp<AbstractLevelDOWN<string, string>>, password: string): Promise<void>;
    lock(): void;
    addWallet(wallet: Wallet): WalletInfo;
    setWalletLabel(id: WalletId, label: string | undefined): void;
    createIdentity(id: WalletId, options: Ed25519Wallet | ReadonlyArray<Slip10RawIndex> | number): Promise<LocalIdentity>;
    setIdentityLabel(id: WalletId, identity: PublicIdentity, label: string | undefined): void;
    getIdentities(id: WalletId): ReadonlyArray<LocalIdentity>;
    signTransaction(id: WalletId, identity: PublicIdentity, transaction: UnsignedTransaction, codec: TxCodec, nonce: Nonce): Promise<SignedTransaction>;
    appendSignature(id: WalletId, identity: PublicIdentity, originalTransaction: SignedTransaction, codec: TxCodec, nonce: Nonce): Promise<SignedTransaction>;
    printableSecret(id: WalletId): string;
}
```

Let's imagine we want to be really opinionated and build a new class.

1. We only support HD keys.
2. We support secp256k1 and ed25519
3. We have one mnemonic we use as a basis for all derivation
4. We maintain a set of accounts (using integer or string id) that can grown 
5. We maintain a list of supported chains, each one with a mapping from "Account" to a derivation path, which can grow.

To serialize, we need the mnemonic (encrypted) as well as the list of accounts and chains.

**Comment by ethanfrey** [comment]
Example interface (please modify, give feedback based on client requirements above, or question those requirements):

(Here I intentionally omit the naming of local identities, we can add that once we find a good agreement how derivations work).

```ts
export type AccountId = string & As<"accountId">;
export interface ChainPath {
  readonly chainId: ChainId;
  readonly algo: "secp256k1" | "ed25519";
  /** Examples are the methods from HdPaths */
  readonly path: (n: int) => ReadonlyArray<Slip10RawIndex>;
};
export interface IdentityQuery {
  readonly chain?: ChainId;
  readonly account?: AccountId;
};
export interface PublicIdentity {
  readonly chain: ChainId;
  readonly account: AccountId;
  readonly address: Address;  // chain-specific address
  readonly pubkey: PublicKeyBundle; // Note: contains algorithm
  readonly path: ReadonlyArray<Slip10RawIndex>;
  // TODO: add label
};

export declare class MultiChainProfile {
    static loadFrom(db: LevelUp<AbstractLevelDOWN<string, string>>, password: string): Promise<MultiChainProfile>;

    readonly createdAt: ReadonlyDate;
    readonly locked: ValueAndUpdates<boolean>;
    readonly accounts: ValueAndUpdates<ReadonlyArray<AccountId>>;
    readonly chains: ValueAndUpdates<ReadonlyArray<ChainPath>>;

    constructor(options?: MultiChainOptions);
    storeIn(db: LevelUp<AbstractLevelDOWN<string, string>>, password: string): Promise<void>;
    lock(): void;

    /** This creates a new account and initializes a PublicIdentity for each Chain */
    createAccount(): Promise<AccountId>;
    /** This adds support for a chain, and adds a new PublicIdentity for each existing Account */
    addChain(chain: ChainPath): Promise<void>; 

    getIdentities(query: IdentityQuery): ReadonlyArray<PublicIdentity>;

    signTransaction(identity: PublicIdentity, transaction: UnsignedTransaction, codec: TxCodec, nonce: Nonce): Promise<SignedTransaction>;
    appendSignature(identity: PublicIdentity, originalTransaction: SignedTransaction, codec: TxCodec, nonce: Nonce): Promise<SignedTransaction>;

    // TODO: maybe rename... we can guaranteed it is mnemonic in this case.
    printableSecret(): string;
}
```

**Comment by ethanfrey** [comment]
In fact, if we go this route with an opinionated wrapper class, I would leave the `UserProfile` untouched, and handle all the chainId stuff and mappings in that wrapper class (including throwing errors if signing a tx on a chain other than the one the identity is registered on).

**Comment by webmaster128** [comment]
> In fact, if we go this route with an opinionated wrapper class, I would leave the UserProfile untouched, and handle all the chainId stuff and mappings in that wrapper class (including throwing errors if signing a tx on a chain other than the one the identity is registered on).

This is exactly what I think. What you describe above is a very specific use case at a very high abstraction level and I don't think it fits into IOV-Core as a generic purpose library. Especially the idea of using 1 account (or however you want to call it) over multiple chains is nothing that is used anywhere else than our wallet.

**Comment by ethanfrey** [comment]
After some discussion with Simon, I support this issue:

* All my comments for functionality should go into some `IdentityManager` that can be implemented in the Wallet application to provide whatever functionality we need.
* Add chainId to all Identities in `UserProfile`, which can then easily get a unique address from the signer, as Simon suggested above.
* Update interface on `MultiChainSigner`, so one could drop in `IdentityManager` as an alternative to `UserProfile` (will make PR now).
