### ISSUE TITLE
Make Lisk, RISE, Ethereum? available by default in cli

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#631]
Right now you probably cannot use the packages because they are not a dependency of @iov/cli

**Comment by antoineherzog** [comment]
As a getting started for new developper regarding IOV-core, i think it would be great to attract potential new hire or extand our developper community. Also, I can do a blog post as well on our medium page or even a youtube video.

**Comment by webmaster128** [comment]
Done by  #742
