### ISSUE TITLE
Add BIP44-like HD path helpers for account based coins

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#634]
There are _BIP44-like_ HD paths for account based coins:

```
m/44'/<coin_type>'/<account index>'
```

following [Trezor's recommendation](https://github.com/trezor/trezor-core/tree/master/docs/coins) that

> If the coin is UTXO-based the path should have all five parts, precisely as defined in BIP-32. If it is account-based we follow Stellar's SEP-0005 - paths have only three parts 44'/c'/a'.

We call them _BIP44-like_ because they are not [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) compatible since they use 3 instead of 5 components.

Derivation paths wee need for our software

```
m/44'/234'/a'   IOV
m/44'/134'/a'   Lisk
m/44'/1120'/a'  RISE

// maybe later
m/44'/148'/a'   Stellar
```

**Comment by ethanfrey** [comment]
Useful helper. Can we put this in 0.11 as well, seems quite easy
