### ISSUE TITLE
Migrate transaction .chainId and .signer into .creator

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#640]
Convert `UnsignedTransaction.chainId` + `UnsignedTransaction.signer` into

```ts
interface UnsignedTransaction {
  creator: PublicIdentity;
  // ...
}
```

This consistes of two aspects:

* Merging `chainId` and `signer` into a combined object of type `PublicIdentity`
* Use the term "creator" as a better name when you think of multi signatures

**Comment by ethanfrey** [comment]
I like this idea as well, simpler API
