### ISSUE TITLE
Remove identity arguments from UserProfile.signTransaction

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#641]
The identity we pass must match the transaction creator. Thus the data is redundant and the `identity: PublicIdentity` argument can be removed.

Current interface

```ts
  public async signTransaction(
    id: WalletId,
    identity: PublicIdentity,
    transaction: UnsignedTransaction,
    codec: TxCodec,
    nonce: Nonce,
  ): Promise<SignedTransaction>
```

**Comment by ethanfrey** [comment]
I like this idea quite a bit. We need to explicitly set in in appendSignature, but the original signing is already clear.

As a proposal for a future PR, if you like it, is for Keyring to enforce a PublicIdentity (chainId, algorithm, publicKey) is globally unique over all wallets. Then we can remove WalletId (implementation detail) and let the Keyring handle the dispatch.  It could loop over all Wallets looking for a match or keep a mapping internally for id to wallet (optional optimization).

This is not for this PR, but related... more an issue proposal if you like to take it on
