### ISSUE TITLE
Allow flexible fractionalDigits in bns sendTx

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#647]
An experience with @iov/cli:

```
>> .editor                                                                                          
// Entering editor mode (^D to finish, ^C to cancel)                                                
const sendTx: SendTransaction = {                                                                   
  kind: "bcp/send",                                                                                 
  chainId,                                                                                          
  signer: ed.pubkey,                                                                                
  recipient: rcpt,                                                                                  
  amount: { quantity: "15", fractionalDigits: 1, tokenTicker: "IOV" as TokenTicker}                 
  };                                                                                                
                                                                                                    
undefined                                                                                           
>> const resp = await signer.signAndPost(sendTx, ewallet.id)                                        
Error: Fractional digits must be 9 but was 1                                                        
    at Generator.next (<anonymous>)                                                                 
    at UserProfile.<anonymous> (/home/ethan/.nvm/versions/node/v10.6.0/lib/node_modules/@iov/cli/nod
e_modules/@iov/keycontrol/src/userprofile.ts:189:42)                                                
    at Object.bytesToSign (/home/ethan/.nvm/versions/node/v10.6.0/lib/node_modules/@iov/cli/node_mod
ules/@iov/bns/src/bnscodec.ts:23:19)                                                                
    at Object.buildUnsignedTx (/home/ethan/.nvm/versions/node/v10.6.0/lib/node_modules/@iov/cli/node
_modules/@iov/bns/src/encode.ts:99:15)                                                              
```

I understand enforcing the 9 when decoding from the blockchain, but if I want to send 1.5 IOV, why not like above: `{ quantity: "15", fractionalDigits: 1, tokenTicker: "IOV" as TokenTicker}`. We should be flexible here, and only throw errors if we specify a fractional precision greater than the blockchain can handle (eg. `{quantity: "1", fractionalDigits: 12}`.

**Comment by webmaster128** [comment]
This makes it very complicated to compare whole transactions using deep equality in tests, as it introduces multiple representations of the same value.

Given that there are a lot of requirements for the Amount type upcoming, it is impossible to keep it as simple as it is now but also as powerful as required. Thus I propose converting the Amount interface into the following class:


```ts
class Amount {
  static fromUserInput(input: string, fractionalDigits: number, tokenTicker: TokenTicker);
  static fromJson(json: { whole: string, fractional: string, fractionalDigits: number, tokenTicker: string  });

  readonly whole: Uint64;
  readonly fractional: Uint64;
  /** the native fractional digits of the token */
  readonly fractionalDigits: number;
  readonly tokenTicker: TokenTicker;

  constructor(whole: Uint64 | number, fractional: Uint64 | number, fractionalDigits: number, tokenTicker: TokenTicker);

  toNumericApproximation(): number;

  /** For debugging purposes. "<whole>.<fractional> <ticker>" */
  toString(): string;

  /**
  * An object like { "whole": "15", "fractional": "444", "fractionalDigits": 9, "tokenTicker": "IOV"  }
  * for 15.000000444 IOV
   */
  toJson(): { whole: string, fractional: string, fractionalDigits: number, tokenTicker: string  };

  /** amount represented as native atomic units for that token */
  toAtomics(): string;

  // all the math you need (equals, <, <=, >, >=, add, substract)
}
```

the above call would then be

```ts
  amount: new Amount(15, 0, 9, "IOV" as TokenTicker),
```

or

```ts
  amount: Amount.fromUserInput("15.0", 9, "IOV" as TokenTicker),
```

This class

- can be implemented to have a unique representation to allow deep equal to work
- can hold the full Ethereum range
- is relativly easy to construct
- should work without an issue in JavaScript

**Comment by ethanfrey** [comment]
I have code in wallet-demo that handles the user input to Amount and back, which works fine and belongs there (no need to overload iov-core).

However, if you look at https://github.com/iov-one/wallet-demo/blob/master/src/logic/balances.ts#L41-L101 you will see three utilities, `trimAmount` to produce minimal fractionaDigits without losing info, `padAmount`, which appends 0s to extend to exactly N fractionalDigits, and `compareAmounts` which performs what you wish to have from the deep equals (you get -1 for less, 0 for equals, and 1 for more to be consistent with sort function output.

When I send a transaction in the client, I would just like to send a valid amount, and not worry about the exact number of fractional digits. The iov-core library can use `padAmount` to pad as needed before parsing. If I try to send 12 fractionalDigits in bns, it will fail naturally, but if I set 4 for ETH, IOV, LISK... why an error?

If this is an issue with test code needing deepEquals, you can use `compareAmounts` for the assertions.

**Comment by ethanfrey** [comment]
I like the simplicity of now and don't want to add more to it (add those in helper functions client side). All I want is that when I send a transaction with less precision than needed, that the codecs can handle it. If you import two of the linked functions, this should be a simple extension, without modifying amount at all

**Comment by ethanfrey** [comment]
After discussion, we decided to expose the `fractionalDigits` in `BcpTicker` and enforce/pad this client side.

This issue was a solution for dealing with missing info. Best solution is to provide the info.
Will create new issue
