### ISSUE TITLE
Waiting on committed transaction hangs forever on error

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#677]
I use this on the result of `signAndPost`. It errors when the call errors, and resolved when the delivertx works, but when the delivertx errors, it never ends... no error is thrown.

Not sure if this an issue in ValueForUpdate.waitFor or that the updates on PostTx don't contain errors.

```ts
// this waits for one commit to be writen, then returns the response
export async function waitForCommit(req: Promise<PostTxResponse>): Promise<PostTxResponse> {
  const res = await req;
  await res.blockInfo.waitFor(info => info.state === BcpTransactionState.InBlock);
  return res;
}
```

**Comment by webmaster128** [comment]
When a node accepts a transaction but the consensus decides to never include it in a block, this is the expected behaviour. The deliverTx result is only available in `BroadcastTxCommitResponse`, not `BroadcastTxSyncResponse`. Not great, but expected.

There are a number of ways to trigger this, e.g. submitting two sends to two nodes from an account that only has money for one to be processed; submitting the same nonce to two nodes …

In Lisk at least a basic balance check is done at submission time, but I don't know if that is done in weave.

**Comment by ethanfrey** [comment]
In tendermint, Checktx is performed before returning BroadcastTxSyncResponse, meaning basic checks pass, but not a guarantee (more a first filter)

After this, it should make it in a block, although it may be included in the block with an error result. 

We should test this case, where Checktx passes, and delivertx fails. 

I will look for such cases in weave and write a proper test case.

**Comment by ethanfrey** [comment]
BLocked until ethan pushes some example code.

**Comment by ethanfrey** [comment]
The error is due to the fact that `listenTx` filters out all errors:

```ts
  public listenTx(query: BcpTxQuery): Stream<ConfirmedTransaction> {
    const chainId = this.chainId();
    const rawQuery = buildTxQuery(query);
    return this.tmClient
      .subscribeTx(rawQuery)
      .filter(transaction => {
        // Filter out events of transactions that did not make it into a block (like commit error events)
        const inBlock = transaction.result.code === 0;
        return inBlock;
      })
      .map(
        (transaction): ConfirmedTransaction => ({
          height: transaction.height,
          confirmations: 1, // assuming block height is current height when listening to events
          transactionId: Encoding.toHex(transaction.hash).toUpperCase() as TransactionId,
          log: transaction.result.log,
          result: transaction.result.data,
          ...this.codec.parseBytes(new Uint8Array(transaction.tx) as PostableBytes, chainId),
        }),
      );
  }
```
Note: `// Filter out events of transactions that did not make it into a block (like commit error events)`

(Also, searchTx doesn't have any handling for errors, which needs to be fixed)

**Comment by ethanfrey** [comment]
So currently, `const searchResult = await toListPromise(this.liveTx({ id: transactionId }), 1);` in `postTx` will never resolve if there is an error.

We need to fix this query but then also update how it is exposed.

I have two proposals to expose this info on `postTx`:

* Update `export declare type BcpBlockInfo = BcpBlockInfoPending | BcpBlockInfoInBlock;` to `export declare type BcpBlockInfo = BcpBlockInfoPending | BcpBlockInfoInBlock | BcpBlockInfoFailed;`
* Close the stream with an error if the transaction fails

Then we can also update listenTx and searchTx...

**Comment by webmaster128** [comment]
`PostTxResponse.blockInfo` is of type `ValueAndUpdates`, i.e. a field that has a mutable value and the additional functionality that you can subscribe to value changes. However, listening to `blockInfo.updates` and polling the `blockInfo.value` should always be equally good ways to access the value. Thus I think the error should be represented as a `BcpBlockInfo`.

Since Tendermint errors seem to be "in block" as well, I suggest

```ts
type BcpBlockInfo = BcpBlockInfoPending | BcpBlockInfoSucceeded | BcpBlockInfoFailed
```

where `BcpBlockInfoSucceeded` is a renaming of the current `BcpBlockInfoInBlock`

**Comment by webmaster128** [comment]
What about splitting the API into

1. Track a single transation with known hash
2. Find transactions that match certain criteria

I think the API is too general. In the implementation side we always split the cases:
- https://github.com/iov-one/iov-core/blob/ac32e32/packages/iov-ethereum/src/ethereumconnection.ts#L414-L437
- https://github.com/iov-one/iov-core/blob/ac32e32/packages/iov-lisk/src/liskconnection.ts#L312-L326
And the caller also wants to either do 1. or 2.

In such a split, 1. could report erros and 2. skip errored transactions

**Comment by ethanfrey** [comment]
I like that.

So `searchTx`/`listenTx` for any query (keep as it is now, just don't handle id/hash queries)
And `searchExactTx`/`listenExactTx` for exact matches

**Comment by ethanfrey** [comment]
And `postTx` could use `listenExactTx` internally, right?

This will break almost no client code of search/listen/live and we can fix it all up inside iov-core.
I also agree that we need to rethink how we do the "query by account" type api

**Comment by webmaster128** [comment]
For the exact transaction search, we only need a single search-or-wait function, right? At least this is what postTx needs. Thus I propose

```ts
/**
 * Looks up transaction in history and if now found, waits until it is available.
 * 
 * As a consequence, this never resolves for non-existing transaction IDs.
 */
public async waitForTransaction(id: TransactionId): Promise<ConfirmedTransaction | FailedTransaction> {
```

**Comment by webmaster128** [comment]
Should waitForTransaction get a timeout (like 5 minutes)? Or chain-dependent?

**Comment by ethanfrey** [comment]
I would say an optional Timeout.

Timeout <= 0 means never timeout

Timeout > 0 times out after that many seconds

Undefined means Timeout with chain-specific default value. 

Sounds good?

**Comment by webmaster128** [comment]
> Sounds good?

Sounds like too many options for no clear reason/requirements. I'll keep it simple and without timeout for now.
