### ISSUE TITLE
Support Multisig Middleware in BnsConnection

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#678]
`x/multisig` allows us to create a multisig contract and update the owners per normal transactions. I also allows us to "activate" a multisig by including all needed signatures and then passing the multisig id in a middleware.

We should add support for those transactions and for the usage of multisig. This is an essential feature for launch, and even testnet security

**Comment by webmaster128** [comment]
@ethanfrey is all we need to start working on this ticket included in weave 0.14.0?

**Comment by ethanfrey** [comment]
Yes, multisig has been implemented as of weave 0.9 or so...

It is a field in the Tx (same level as Fee), which accepts an array of mutlisig ids. For some idea of the usage of the contract: https://github.com/iov-one/weave/blob/master/x/multisig/decorator_test.go

There are also two message to create and update the contract in the first place (before it can be used): https://github.com/iov-one/weave/blob/cb5386a6e341eeb26237754a9928000825a72065/x/multisig/codec.proto#L28-L40 and it can also be created in genesis for testing. https://github.com/iov-one/weave/blob/cb5386a6e341eeb26237754a9928000825a72065/cmd/bnsd/app/testdata/fixtures/app.go#L89-L103

If you have any other questions on the weave spec, please feel free to ask here or in slack.

**Comment by ethanfrey** [comment]
It depends how you add the types.

It may be an optional field in the bcp transactions that is only supported by bns. Or you may make refinements of the types (eg. `SendTransaction & WithCreator & WithMultisig`) in the iov-bns package.

Requirement is only that it works for bns. How you handle clean APIs and types is your call (may affect bcp if you wish)

**Comment by willclarktech** [comment]
Closed in #985
