### ISSUE TITLE
Remove BcpAccount.name and SetNameTx

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#683]
- [ ] Remove BcpAccount.name
- [ ] Remove SetNameTx
- [ ] Adapt "Register a BNS name" README section

BcpAccount.name was only used for BNS wallet nicknames, which we don't need anymore.

@ethanfrey can we safely remove SetNameTx? This will remove support for existing SetNameTx parsing. Whenever a client encounters such a transaction, there will be a "unknown message type in transaction" exception.

**Comment by ethanfrey** [comment]
:+1:

Please do. This can go in 0.11 as well. 0.10 is last one we need SetName on, and we are transitioning the last client off of it.

**Comment by ethanfrey** [comment]
It can also go in 0.12, no rush
