### ISSUE TITLE
Wrong testnet URL

### ISSUE THREAD

**Issue by albertandrejev** [iov-one/iov-core#689]
https://github.com/iov-one/iov-core/blob/master/packages/iov-core/README.md contains wrong link to testnet (https://bov.friendnet-fast.iov.one/). It shows "Server not found" error.

**Comment by webmaster128** [comment]
Thanks Albert! I guess you found a developer network for your own work by now.

I'll keep this ticket open and fix as soon as the next public long term support network (hugnet) is deployed

**Comment by webmaster128** [comment]
Here is a list of our testnets: https://github.com/iov-one/ops/wiki/Testnet-list

Everything referring to friendnet should be updated
