### ISSUE TITLE
Remove BnsConnection.status()

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#716]
This exists for no clear reason and is not tested

**Comment by ethanfrey** [comment]
It is covered in the tm client tests and we use the tm client.status to get the height.

That said, I don't know if it needs to be exposed at this level. Tm client.status is quite useful

**Comment by webmaster128** [comment]
Jap, this ticket is only about the high level exposure in BnsConnection. Tm client.status sould stay untouched.
