### ISSUE TITLE
Update Readme with proper 0.11.x upgrade

### ISSUE THREAD

**Issue by LucasIsasmendi** [iov-one/iov-core#736]
- [ ] `profile.createIdentity` without chainId

**Comment by ethanfrey** [comment]
Huh? You mean it is not listed as a breaking change?
Or you want a way to do it?

You need to provide a chainId

**Comment by LucasIsasmendi** [comment]
I mean the readme examples on each package, probably they are based on old versions, like `createIdentity` which requires chainId as a new parameter after the 0.11 release.
