### ISSUE TITLE
signAndPost does not propagate error

### ISSUE THREAD

**Issue by LucasIsasmendi** [iov-one/iov-core#769]
When adding ethereum to wallet-demo, `signAndPost` does not get "throw new Error("gasPrice must be set");" from `signTransaction`. So there is a missed error propagation, hard to notice when something is missed.

**Comment by webmaster128** [comment]
Reviewed all the code in IOV-Core and cannot find the issue. Are you sure this is not caused by the caller application? Can you reproduce with a test in https://github.com/iov-one/iov-core/blob/master/packages/iov-core/src/multichainsigner.spec.ts or the CLI?
