### ISSUE TITLE
get pubkey from ethereum transaction

### ISSUE THREAD

**Issue by LucasIsasmendi** [iov-one/iov-core#770]
In wallet-demo we need to get the pubkey when we do `liveTx`, this calls function `parseBytesTx` from ethereum class Scraper. 
We can get the pubkey because we know the signature from scraper [Get public key of any ethereum account](https://ethereum.stackexchange.com/questions/13778/get-public-key-of-any-ethereum-account)

- [x] Calculate pubkey from signature
- [x] Make signature available in liveTx

**Comment by webmaster128** [comment]
The signature -> pubkey algorithm is indeed not yet implemented but we should have it.

However, in this particular case the issue is that a scraper transaction result does not contain the signature:

```js
{ blockNumber: '3926442',
  timeStamp: '1551025714',
  hash:
   '0x85aa4bee170b4965b550c9848830ac90e0893be1e795f0d0d82a662bb7013b8b',
  nonce: '463',
  blockHash:
   '0xd5c16d5e625c6d3ee4f6cc7bb7e950717ef6a6e90874daa9b79562b055a88276',
  transactionIndex: '5',
  from: '0x0a65766695a712af41b5cfecaad217b1a11cb22a',
  to: '0x3e6eee4a17f4755249f642573ac968fd5772473b',
  value: '445500',
  gas: '141000',
  gasPrice: '1000000000',
  isError: '0',
  txreceipt_status: '1',
  input:
   '0x6c697665547828292074657374204120302e3134303835323432303733363937303133',
  contractAddress: '',
  cumulativeGasUsed: '486275',
  gasUsed: '23380',
  confirmations: '2' }
```

Thus we need to call a searchTx for every transaction result in order to get the missing information.

**Comment by webmaster128** [comment]
Done in 0.12 branch
