### ISSUE TITLE
Tendermint start script: default port does not match default version

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#776]
Seems like a new port-numbering system was introduced but the default port in the Tendermint start (single) script wasn't updated. Currently it's set to `12345` but it should now be `11125` (unless we want to update it for v0.29 instead). This breaks the workflow described in the README. It might be better to update the README to use the `all_start.sh` script anyway, since that's the only way to get a fully passing test suite.

**Comment by webmaster128** [comment]
Correct. Only the ports `111<minor version>` should be used. Thus I think the start script should fail TENDERMINT_VERSION, TENDERMINT_PORT or TENDERMINT_NAME is unset instead of defaulting to outdated values.
