### ISSUE TITLE
Lisk: reuse repo clone across start and stop scripts

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#778]
We currently clone the Lisk repo separately in the start and stop scripts, but I couldn't see any reason not to reuse the repo if it was already cloned.

**Comment by webmaster128** [comment]
The reason is it is cloned into an unknown temporary directory (since it is only needed temporarily). This operation only takes 3 seconds (see https://github.com/iov-one/wallet-demo/issues/263#issuecomment-459989542), which is not a relevant factor in the starting process.

**Comment by webmaster128** [comment]
I think in general we should reduce the number of network requests during the development process to also allow working on bad or no internet scnerarios. In this case we need
1. Use a fixed location (can be a static subfolder of `${TMPDIR:-/tmp}`)
2. Find git commands to detect checkout, match tag, fetch if needed

**Comment by webmaster128** [comment]
Done in #963
