### ISSUE TITLE
Remove BnsConnection.changeNonce, .changeBalance, .changeTx

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#792]
all unused

**Comment by willclarktech** [comment]
@webmaster128 Should`watchAccount` also be removed? https://github.com/iov-one/iov-core/blob/master/packages/iov-bns/src/bnsconnection.ts#L614

**Comment by webmaster128** [comment]
Nope, watchAccount is part of the BCP interface (see BcpConnection) and used in the wallet
