### ISSUE TITLE
Convert all implementations of UnsignedTransaction to simple types

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#799]
In the first step, all types must be in the [List of supported types of the structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#Supported_types). Later we need to be able to JSON encode them, so prefer simple types over complex types.

As far as I can see this only affects the type `Nonce`, which is a complex class at the moment. Nonce can be converted to a number with the restriction that it must be in the safe integer range.

**Comment by ethanfrey** [comment]
For classes like Int53, can't you just used tagged types to give compile time (no runtime) guarantees.

Like `type Nonce = number & As<"Int53">`

And then have a `func toNonce(n: number): Nonce` that throws an error on out of bounds values, or
`func isNonce(n: number): n is Nonce` guard.

I like having some checks of the range, and if we just have the compiler help us ensure the numbers were checked somewhere before using them, that should be enough

**Comment by webmaster128** [comment]
> For classes like Int53, can't you just used tagged types to give compile time (no runtime) guarantees.

Jap, exactly.
