### ISSUE TITLE
Send ERC20 tokens

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#813]
Builds on #812 

- [ ] Make a unique transaction type to send a given ERC20 token to a new account.
- [ ] Ethereum Codec can encode/decode this transaction properly
- [ ] It is executed on the chain and updates balances as expected.

**Comment by webmaster128** [comment]
>  Make a unique transaction type to send a given ERC20 token to a new account.

Why do you think we cannot encode that token send in a bcp/send transaction?

**Comment by ethanfrey** [comment]
We need a lookup table to translate, as there is info in the ERC20 transfer (such as the token name -> address + sig figs) that is not present in `bcp/send` and must come from somewhere.

I meant this to be a simple step, as you like smaller, clear issues, and then #814 would handle doing that mapping transparently, "under the hood".
