### ISSUE TITLE
Select good generic atomic swap contract

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#817]
We should start with some existing code to see how it works and what we want from it.

Let's pick a contract, and when selected, flatten it and add to scripts as in #809 

Some ideas:
- Minimal contract (create one per swap): https://github.com/realcodywburns/Tank-Farm/blob/master/contracts/locking/HTLC%28mew%29.sol and [described here](https://medium.com/@DontPanicBurns/ethereum-cross-chain-atomic-swaps-5a91adca4f43)
- A more complex one that can be reused and supports eth and erc20: https://github.com/jchittoda/eth-atomic-swap

Let's make sure we all (at least Simon and Will) understand how this contract works

**Comment by webmaster128** [comment]
Done. The second one does exactly what we need and was used as a great source of inspiration to implement our own logic and naming. Thanks for finding those resources.
