### ISSUE TITLE
Create transactions for simple ETH-ETH atomic swap (one chain)

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#818]
Builds on #817 

Add some custom ethereum transactions and execute an atomic swap.

Use two different copies of the same contract on one ganche chain, so they think they are separate.

As this would be second specific contract call (after erc20 example), this should include refactoring the generic "abi contract call" transaction to work for the more general case.
 
Note: we could also start up to local ganache chains and swap between them if not too much overhead to set up

**Comment by webmaster128** [comment]
To get this done as simple as possible in our existing setup, I suggest the following steps:

1. Deploy Ether atomic swap contract (see a. https://github.com/iov-one/iov-core/tree/master/scripts/ethereum/deployment/contracts b. https://github.com/iov-one/iov-core/blob/master/scripts/ethereum/deployment/contracts.json c. https://github.com/iov-one/iov-core/blob/master/scripts/ethereum/deployment/package.json#L10 d. https://github.com/iov-one/iov-core/blob/master/scripts/ethereum/deployment/src/deploy_contracts.ts#L8 e. https://github.com/iov-one/iov-core/blob/master/scripts/ethereum/deployment/src/deploy_contracts.ts#L41 f. https://github.com/iov-one/iov-core/blob/master/scripts/ethereum/init.sh#L14-L16 g. https://github.com/iov-one/iov-core/tree/master/scripts/ethereum#startstop)
2. Test one-sided swap offer handling similar to https://github.com/iov-one/iov-core/blob/v0.13.0/packages/iov-bns/src/bnsconnection.spec.ts#L1623-L1911
3. Do an ETH-ETH atomic swap in @iov/ethereum using the same contract instance (address printed as part of 1.)

The cross-contract case can easier be tested by integrating Ethereum into `packages/iov-core/src/integrationtests/atomicswap.spec.ts`. So we can go for cross-chain straight.

**Comment by ethanfrey** [comment]
(1) and (2) are good prep, and I think related to other issues.

Updating (3) would solve it, and if you want to go right to ETH-IOV swap in that integration test, you can close two issues in one step :)
