### ISSUE TITLE
RegisterBlockchainTx with empty codecName leads to invalid signature

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#836]
```
Error: {
  "data": {},
  "log": "Signature invalid",
  "code": 3,
  "hash": {
    "0": 19,
    "1": 153,
    "2": 253,
```

**Comment by ethanfrey** [comment]
Issue with how golang protobuf works...

We enforce canonical Form. 
Which means zero values... 0, false, "", empty bytes, etc should be replaced by undefined. Same as with the memo field in SendTx.

**Comment by webmaster128** [comment]
Closing as this transaction type does not exist anymore in IOV-Core 0.14+. Hugnet clients just need to set a codecName.
