### ISSUE TITLE
Add support for BNS 0.12

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#843]
IOV-Core 0.13.x is the last branch compatible with BNS 0.11 (Hugnet) and can receive patch releases as needed. Current master can be changed to BNS 0.12 support.

- [ ] Update compatibility table in iov-bns REDME
- [ ] Update iov-bns

**Comment by ethanfrey** [comment]
We actually will need 0.13.0 support ;) which is deployed on zebranet.

But the only change that affects iov-core is that we use timestamp for timeout on escrow.
I would like to change the bcp.atomicswap definitions to use time as well, which they can convert to block height "under the hood" for ethereum. As a library user will understand "in 1 week", but not necessarily want to write the logic to figure out what block height that is for each chain.

I will complete this to update fees, and add a second issue for handling escrow
