### ISSUE TITLE
Cleanup Ethereum RPC client

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#853]
Right now, the EthereumConnection uses two different connections

* HTTP for all basic RPCs,
* Websocket for subscriptions.

It would be nice to have a generic EthereumRpcClient that uses a different implementation depending on the base URL (very similar to [the Tendermint-RPC Client](https://github.com/iov-one/iov-core/blob/v0.13.0/packages/iov-tendermint-rpc/src/client.ts#L11-L12)). This EthereumRpcClient does not have subscription functionality when used with a http implementation.

This can be split into two steps:

1. Update implementation respecting `baseUrl` and `EthereumConnectionOptions.wsUrl` in an intelligent way
2. Remove field `EthereumConnectionOptions.wsUrl` (API breaking)

**Comment by willclarktech** [comment]
@webmaster128 Step 2 should go into v0.15?

**Comment by webmaster128** [comment]
@willclarktech yes, since breaking.

Step 1:

We have up to 2 sources for node URLs, `baseUrl` and `EthereumConnectionOptions.wsUrl` and should find a clever algorithm that always uses the better one. I.e. as soon as there is a WS URL, we ignore the HTTP URL.

Step 2:

Cleanup by removing `EthereumConnectionOptions.wsUrl`. The connection type is now only determined by the URL schema in `baseUrl`.

**Comment by willclarktech** [comment]
@webmaster128 Is WS definitely always preferable to HTTP? Eg could someone provide both because they want to use HTTP where possible but they still want to use the streaming methods that rely on WS?

**Comment by webmaster128** [comment]
@willclarktech I was never facing a case where a WS connection was possible but HTTP was preferred. In some cases the stateless HTTP is better/easier, but as soon as a WS URL is provided and WS is used, it is safe to assume everything should go via WS.

**Comment by willclarktech** [comment]
Closed in #1050
