### ISSUE TITLE
Test ERC20 support with 5-10 popular tokens on rinkeby

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-core#854]
Make sure that all code that works on CI also works on live networks.

This may involved revistiing #816 to use etherscan if the logs are not available

**Comment by webmaster128** [comment]
For testing we're a bit limited to tokens that we have access to (via faucets or similar). Those are the ones we are using

- [x] [Wrapped Ether (WETH)](https://rinkeby.etherscan.io/address/0xc778417e063141139fce010982780140aa0cd5ab): get tokens via deposit method
- [x] [Avocado (AVO)](https://rinkeby.etherscan.io/address/0x0c8184c21a51cdb7df9e5dc415a6a54b3a39c991): get tokens via [this faucet contract](https://rinkeby.etherscan.io/address/0x8c2451d9bebc7c18ca89fdf7db8692d51605c04b)
- [ ] [Test Golem Network Token (tGNT)](https://rinkeby.etherscan.io/address/0x7295bb8709ec1c22b758a8119a4214ffed016323): there is a create() function in the token contract (see [this transaction](https://rinkeby.etherscan.io/tx/0xc08fe263844e057dd85a8f59e80cc81cac32a75a36ada59e5e63077baba3f547)) and we can possibly call it

More items for this list are highly welcome

**Comment by ethanfrey** [comment]
That list is also good enough to close this issue... 5-10 may have been overkill, just wanted to capture if there were important differences "in the wild"

**Comment by webmaster128** [comment]
Another nice set of test token contracts: https://ethereum.stackexchange.com/a/68072
