### ISSUE TITLE
Migrate to eslint

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#876]
This should be done on the master branch at some point when there is no heavy development on a different branch anymore to avoid unnecessary merge work.

Prerequirements

- [x] ERC20 support in 0.13 completed
- [x] 0.13.x with ERC20 support integrated into wallet-demo
- [x] ERC20 in wallet-demo tested
- [x] 0.13.x integrated into [ponferrada](https://github.com/iov-one/ponferrada)
- [x] Merge https://github.com/iov-one/iov-core/pull/987 first to reduce diff of this PR
- [x] Merge obsolete `tslint_ci.json` into `tslint.json` and remove `TSLINT_FLAGS`
- [x] Base on branch 0.14, which we may need to support for some more time
- [x] Use configuration format that supports comments ~(yaml (preferred by me) or [js](https://github.com/iov-one/ponferrada/blob/master/.eslintrc.js))~ json
- [x] Start with any ruleset that leaves the current code unchanged
- [x] Ignore `docs/` as commented above
- [x] Turn disabled rules back on and fix errors
- [ ] Remove (or convert) "tslint:" comments

https://github.com/iov-one/ponferrada uses eslint for TypeScript already, so we can get some of the setup from there.

**Comment by willclarktech** [comment]
@webmaster128 OK to close this and open another issue when we're ready to get rid of tslint?

**Comment by webmaster128** [comment]
Perfect
