### ISSUE TITLE
Improve UserProfile API for many store operations

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#898]
When a caller needs to store the UserProfile very often (i.e. after every change), we should not run Argon2 on the password every single time.

**Comment by willclarktech** [comment]
How about a configurable timeout like git commit signing?

**Comment by webmaster128** [comment]
The Argon 2 parameters are fixed right now (see also https://github.com/iov-one/iov-core/issues/147) and it is non-trivial to make them dynamic. The overall plan looks something like this:

1. Extract `password -> encryption key` into a separate standalone function and take the encryption key instead of the password in `loadFrom`/`storeIn` (this ticket). This allows the caller to cache the  encryption key.
2. Use a WebWorker in the wallet to perform Argon 2 in a separate thread, avoid blocking the UI.
3. Increase Argon 2 parameters (#147)
4. (in my dreams) Improve Argon 2 speed by dependency injetion of native code (since [the WebAssemby version is very slow](https://github.com/jedisct1/libsodium.js/issues/133))
5. (nice to have) Add intelligence to dynamically calculate suitable Argon 2 parameters. This requires storing the parameters in plaintext next to the encrypted content in oder to be able to decrypt.

**Comment by willclarktech** [comment]
@webmaster128 OK to close?

**Comment by webmaster128** [comment]
Done in #1026
