### ISSUE TITLE
Update BNS for 32 byte preimage

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#899]
Currently in the BNS tests we use lines like this:
```
const preimage1 = Encoding.toAscii("the first swap is easy") as Preimage;
```
But with our current design, the preimage should be exactly 32 bytes (we have a helper for making them). This should also be enforced blockchain-side.

**Comment by webmaster128** [comment]
Right. Created a ticket in the weave repo for this: https://github.com/iov-one/weave/issues/510

**Comment by willclarktech** [comment]
We'll need to update to update our tests as well though.

**Comment by webmaster128** [comment]
You are right. But I'd prefer to see the test failing as part of a weave upgrade to be sure that test actually exists on chain. When we update the test now, nobody will ever check that from the client side.
