### ISSUE TITLE
Switch to jasmine-spec-reporter

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#928]
`jasmine-console-reporter` provides no way to configure the specs section of the console output, meaning whenever you're running a subset of tests you have to scroll up a lot to find the results/logging output you're looking for. `jasmine-spec-reporter` allows you to specify what you want to see with much more granularity.

https://github.com/bcaudan/jasmine-spec-reporter/blob/master/src/configuration.ts

**Comment by willclarktech** [comment]
Superseded by #953

**Comment by willclarktech** [comment]
Reopening as we're not switching to Jest anytime soon.

**Comment by webmaster128** [comment]
Done in #1086
