### ISSUE TITLE
Convert swap IDs to objects

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#938]
Currently we model swap IDs as byte arrays, but this doesn't provide enough structure for all situations. For example, in order to uniquely identify an atomic swap on the Ethereum blockchain, one needs to know which smart contract contains the swap. (This point is especially clear when considering that—in our implementation—native ETH swaps use a different contract to ERC20 swaps.)

This issue involves changing swap IDs to be objects, which hold a byte array, but which can be extended on a per-chain basis to incorporate more identifying information where necessary.

**Comment by webmaster128** [comment]
`AtomicSwapHelpers.createId` should then be removed from `@iov/bcp` as swap ID structure becomes responsibility of the blockchain connection or codec.

**Comment by webmaster128** [comment]
Geven the new type

```ts
export interface SwapId {
  readonly data: SwapIdBytes;
}
```

from #940, how do you plan to add the contract addresses needed by Ethereum?

**Comment by willclarktech** [comment]
Since each `EthereumConnection` instance stores at most one Ethereum swap contract address and at most one ERC20 swap contract address, the swap ID should only need to encode whether it's an Ethereum or ERC20 swap (I was thinking an `EthereumSwapId` which extends `SwapId` with an `enum`).

**Comment by webmaster128** [comment]
The issue with that approach is:
* The implementation of `EthereumConnection.getSwap` (and similar situations) needs to do a cast to `EthereumSwapId`, which removes a lot of compile time type safety (important for refactorings)
* An equality function between two `SwapId` implemented in `@iov/bcp` gives wrong results when a `EthereumSwapId` is passed by ignoring the eth/erc20 flag.

This I'd suggest adding an optional field to the BCP type, like e.g.

```ts
export interface SwapId {
  readonly prefix?: string;
  readonly data: SwapIdBytes;
}
```

or

```ts
export interface SwapId {
  readonly contractAddress?: Address;
  readonly data: SwapIdBytes;
}
```

In both cases, the only place where this additional field is set is `createEtherSwapId()` and `createErc20SwapId()`. With the second approach, those methods need to become instance methods.

**Comment by willclarktech** [comment]
I like `prefix` as more general.
