### ISSUE TITLE
Fully support getSwaps in Ethereum connection

### ISSUE THREAD

**Issue by willclarktech** [iov-one/iov-core#950]
Currently our Ethereum connection's `getSwaps` implementation supports querying by ID for both ETH and ERC20 token swaps because the prefix will tell the connection which contract to query. For other types of query we don’t have this information. Options here include:
1. A flag to indicate which type of swap is desired, possibly by way of providing an ERC20 contract address to further filter results.
1. Getting both types of swaps and merging them together.
1. Adding additional view functions to the smart contracts themselves.
1. Separate `EthereumConnection` instances for Ether/ERC20 or even each ERC20 token.

**Comment by webmaster128** [comment]
For the user of IOV-Core, especially wallet software, the BCP interface should behave as if there is only one kind of contract. All swaps, no matter wich type, should be returned. So I think 2. is the way to go.
