### ISSUE TITLE
Migrate to Jest

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#953]
I tried conversion package-by-package before but unfortunately, the testing types from @types/jasmine (like `describe` or `it`) are monorepo global. So this is an all or nothing task.

Looks like Jest uses most of the same expect syntax, so Jasmine -> Jest should be easier than Jasmine -> Mocha.

- [x] Migrate from jasmine2-custom-message to Jasmine native [withContext](https://jasmine.github.io/api/edge/matchers.html#withContext) (e.g. [here](https://github.com/jasmine/jasmine/issues/641#issuecomment-457037665)). Not beatiful but we rarely need it and can get rid of one dependency
- [ ] Migrate Jasmine -> Jest

**Comment by willclarktech** [comment]
Task 1 completed: https://github.com/iov-one/iov-core/pull/954

**Comment by webmaster128** [comment]
https://github.com/iov-one/iov-core/pull/954 now backported to branch 0.13 and 0.14

**Comment by webmaster128** [comment]
I stared with this but found a serious limitation: if I understand correctly, jest requires a nodeJS environment and cannot be run in a real browser. This is very unfortunate, since we want to ensure that the real browser's JS engines support our code.

**Comment by karol-depka** [comment]
> I stared with this but found a serious limitation: if I understand correctly, jest requires a nodeJS environment and cannot be run in a real browser. This is very unfortunate, since we want to ensure that the real browser's JS engines support our code.

Hey. Is this for sure? I'm considering migration to Jest for a number of projects too...

**Comment by webmaster128** [comment]
Hi @karol-depka, I jave a few strong indications:

* Whenever you search for running Jest in Karma, you find articles describing a migration Krama -> Jest
* Our frontend team uses Jest+JSDOM, which is a DOM implementation in nodejs. In addition to those JSDOM tests, if I understood correctly, there are end2end tests that spawn a Chrome browser from the running nodejs test (with puppeteer).
* There are those two Jest issues: https://github.com/facebook/jest/issues/139 closed in favour of https://github.com/facebook/jest/issues/848
* Then there is [this guy claiming you can easily run Jest in Karma](https://github.com/facebook/jest/issues/848#issuecomment-450537533) but the [project he refers](https://github.com/kimamula/jest-karma-angular-demo) to is forked from a repo that came along with the article [Testing Angular faster with Jest](https://www.xfive.co/blog/testing-angular-faster-jest/), which states _Farewell browser, our tests now run in jsdom; You can also bump into APIs available in browsers but not in jsdom, like htmlElement.closest or window.localStorage (which we just mocked in jestGlobalMocks.ts)._

**Comment by karol-depka** [comment]
@webmaster128 Thank You very much for taking the time to explain all this! Much appreciated and a great gesture! Cheers!

**Comment by webmaster128** [comment]
Closing this for the reasons described above. We'll not migrate to Jest for now.
