### ISSUE TITLE
BnsConnection import is missing in @iov/cli 

### ISSUE THREAD

**Issue by antoineherzog** [iov-one/iov-core#965]
i tried to test the BNS from IOV-cli (We are preparing a blog post about the BNS functionnality)but I got an error message when I typed the line from the tutorial

const bnsConnection = connection as BnsConnection;

At the line 38 of the file https://github.com/iov-one/iov-core/blob/master/packages/iov-cli/src/cli.ts, we need to add the import, It should be i think:

    ["@iov/bns", ["bnsCodec", "bnsConnector", "bnsConnection", "RegisterUsernameTx"]],

**Comment by webmaster128** [comment]
@antoineherzog right, the `BnsConnection` convenience import is missing. For now (and in case some other import is missing, you can always use the cli to import additional symbols, e.g.

```
import { BnsConnection } from "@iov/bns";
```

**Comment by webmaster128** [comment]
Done in #972. Will be merged from branch 0.13 -> 0.14 -> master at some point today.
