### ISSUE TITLE
Rename package @iov/core

### ISSUE THREAD

**Issue by webmaster128** [iov-one/iov-core#971]
Depends on https://github.com/iov-one/iov-core/issues/917

----------

The package name @iov/core is misleading, as IOV-Core is the name for a whole set of npm packages.

What we really need is a name for high level functionality that is in there.

I suggest @iov/multichain, but am happy for better ideas.

**Comment by willclarktech** [comment]
It would be good to have this on the MVP track to avoid painful renamings afterwards.
